
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 24小时潮位
/// </summary>
/// <returns></returns>
public class sql_TBL24HTIDELEVEL
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBL24HTIDELEVEL()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有24小时潮位预报
    /// </summary>
    /// <returns></returns>
    public object get_TBL24HTIDELEVEL_AllData(TBL24HTIDELEVEL TBL24HTIDELEVEL)
    {

        try
        {
         
            return DataExe.GetTableExeData("select * from TBL24HTIDELEVEL where PUBLISHDATE=to_date('" + TBL24HTIDELEVEL.PUBLISHDATE.ToString()+"', 'yyyy-mm-dd hh24@mi@ss')" );
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增24小时潮位预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBL24HTIDELEVEL(TBL24HTIDELEVEL TBL24HTIDELEVEL)
    {

        string sql = "INSERT INTO  TBL24HTIDELEVEL (PUBLISHDATE,TLSECONDTIMELOWTIDE,TLLOWTIDELEVELFORTHESECONDTIME,TLFORECASTSTANCE,FORECASTDATE,TLFIRSTWAVEOFTIME,TLFIRSTWAVETIDELEVEL,TLFIRSTTIMELOWTIDE,TLLOWTIDELEVELFORTHEFIRSTTIME,TLSECONDWAVEOFTIME,TLSECONDWAVETIDELEVEL) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@TLSECONDTIMELOWTIDE,@TLLOWTIDELEVELFORTHESECONDTIME,@TLFORECASTSTANCE,to_date(@FORECASTDATE,'yyyy-mm-dd hh24@mi@ss'),@TLFIRSTWAVEOFTIME,@TLFIRSTWAVETIDELEVEL,@TLFIRSTTIMELOWTIDE,@TLLOWTIDELEVELFORTHEFIRSTTIME,@TLSECONDWAVEOFTIME,@TLSECONDWAVETIDELEVEL)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var TLSECONDTIMELOWTIDE = DataExe.GetDbParameter();
        var TLLOWTIDELEVELFORTHESECONDTIME = DataExe.GetDbParameter();
        var TLFORECASTSTANCE = DataExe.GetDbParameter();
        var FORECASTDATE = DataExe.GetDbParameter();
        var TLFIRSTWAVEOFTIME = DataExe.GetDbParameter();
        var TLFIRSTWAVETIDELEVEL = DataExe.GetDbParameter();
        var TLFIRSTTIMELOWTIDE = DataExe.GetDbParameter();
        var TLLOWTIDELEVELFORTHEFIRSTTIME = DataExe.GetDbParameter();
        var TLSECONDWAVEOFTIME = DataExe.GetDbParameter();
        var TLSECONDWAVETIDELEVEL = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        TLSECONDTIMELOWTIDE.ParameterName = "@TLSECONDTIMELOWTIDE";
        TLLOWTIDELEVELFORTHESECONDTIME.ParameterName = "@TLLOWTIDELEVELFORTHESECONDTIME";
        TLFORECASTSTANCE.ParameterName = "@TLFORECASTSTANCE";
        FORECASTDATE.ParameterName = "@FORECASTDATE";
        TLFIRSTWAVEOFTIME.ParameterName = "@TLFIRSTWAVEOFTIME";
        TLFIRSTWAVETIDELEVEL.ParameterName = "@TLFIRSTWAVETIDELEVEL";
        TLFIRSTTIMELOWTIDE.ParameterName = "@TLFIRSTTIMELOWTIDE";
        TLLOWTIDELEVELFORTHEFIRSTTIME.ParameterName = "@TLLOWTIDELEVELFORTHEFIRSTTIME";
        TLSECONDWAVEOFTIME.ParameterName = "@TLSECONDWAVEOFTIME";
        TLSECONDWAVETIDELEVEL.ParameterName = "@TLSECONDWAVETIDELEVEL";




        PUBLISHDATE.Value = TBL24HTIDELEVEL.PUBLISHDATE.ToString();
        TLSECONDTIMELOWTIDE.Value = TBL24HTIDELEVEL.TLSECONDTIMELOWTIDE;
        TLLOWTIDELEVELFORTHESECONDTIME.Value = TBL24HTIDELEVEL.TLLOWTIDELEVELFORTHESECONDTIME;
        TLFORECASTSTANCE.Value = TBL24HTIDELEVEL.TLFORECASTSTANCE;
        FORECASTDATE.Value = TBL24HTIDELEVEL.FORECASTDATE.ToString();
        TLFIRSTWAVEOFTIME.Value = TBL24HTIDELEVEL.TLFIRSTWAVEOFTIME;
        TLFIRSTWAVETIDELEVEL.Value = TBL24HTIDELEVEL.TLFIRSTWAVETIDELEVEL;
        TLFIRSTTIMELOWTIDE.Value = TBL24HTIDELEVEL.TLFIRSTTIMELOWTIDE;
        TLLOWTIDELEVELFORTHEFIRSTTIME.Value = TBL24HTIDELEVEL.TLLOWTIDELEVELFORTHEFIRSTTIME;
        TLSECONDWAVEOFTIME.Value = TBL24HTIDELEVEL.TLSECONDWAVEOFTIME;
        TLSECONDWAVETIDELEVEL.Value = TBL24HTIDELEVEL.TLSECONDWAVETIDELEVEL;


        DbParameter[] parameters = { PUBLISHDATE, TLSECONDTIMELOWTIDE, TLLOWTIDELEVELFORTHESECONDTIME, TLFORECASTSTANCE, FORECASTDATE, TLFIRSTWAVEOFTIME, TLFIRSTWAVETIDELEVEL, TLFIRSTTIMELOWTIDE, TLLOWTIDELEVELFORTHEFIRSTTIME, TLSECONDWAVEOFTIME, TLSECONDWAVETIDELEVEL };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改24小时潮位预报
    /// </summary>
    public int Edit_TBL24HTIDELEVEL(TBL24HTIDELEVEL TBL24HTIDELEVEL)
    {
        string sql = "UPDATE   TBL24HTIDELEVEL set	TLSECONDTIMELOWTIDE=@TLSECONDTIMELOWTIDE,TLLOWTIDELEVELFORTHESECONDTIME=@TLLOWTIDELEVELFORTHESECONDTIME,TLFIRSTWAVEOFTIME=@TLFIRSTWAVEOFTIME,TLFIRSTWAVETIDELEVEL=@TLFIRSTWAVETIDELEVEL,TLFIRSTTIMELOWTIDE=@TLFIRSTTIMELOWTIDE,TLLOWTIDELEVELFORTHEFIRSTTIME=@TLLOWTIDELEVELFORTHEFIRSTTIME,TLSECONDWAVEOFTIME=@TLSECONDWAVEOFTIME,TLSECONDWAVETIDELEVEL=@TLSECONDWAVETIDELEVEL where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss') and TLFORECASTSTANCE=@TLFORECASTSTANCE and FORECASTDATE=to_date(@FORECASTDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var TLSECONDTIMELOWTIDE = DataExe.GetDbParameter();
        var TLLOWTIDELEVELFORTHESECONDTIME = DataExe.GetDbParameter();
        var TLFORECASTSTANCE = DataExe.GetDbParameter();
        var FORECASTDATE = DataExe.GetDbParameter();
        var TLFIRSTWAVEOFTIME = DataExe.GetDbParameter();
        var TLFIRSTWAVETIDELEVEL = DataExe.GetDbParameter();
        var TLFIRSTTIMELOWTIDE = DataExe.GetDbParameter();
        var TLLOWTIDELEVELFORTHEFIRSTTIME = DataExe.GetDbParameter();
        var TLSECONDWAVEOFTIME = DataExe.GetDbParameter();
        var TLSECONDWAVETIDELEVEL = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        TLSECONDTIMELOWTIDE.ParameterName = "@TLSECONDTIMELOWTIDE";
        TLLOWTIDELEVELFORTHESECONDTIME.ParameterName = "@TLLOWTIDELEVELFORTHESECONDTIME";
        TLFORECASTSTANCE.ParameterName = "@TLFORECASTSTANCE";
        FORECASTDATE.ParameterName = "@FORECASTDATE";
        TLFIRSTWAVEOFTIME.ParameterName = "@TLFIRSTWAVEOFTIME";
        TLFIRSTWAVETIDELEVEL.ParameterName = "@TLFIRSTWAVETIDELEVEL";
        TLFIRSTTIMELOWTIDE.ParameterName = "@TLFIRSTTIMELOWTIDE";
        TLLOWTIDELEVELFORTHEFIRSTTIME.ParameterName = "@TLLOWTIDELEVELFORTHEFIRSTTIME";
        TLSECONDWAVEOFTIME.ParameterName = "@TLSECONDWAVEOFTIME";
        TLSECONDWAVETIDELEVEL.ParameterName = "@TLSECONDWAVETIDELEVEL";




        PUBLISHDATE.Value = TBL24HTIDELEVEL.PUBLISHDATE.ToString();
        TLSECONDTIMELOWTIDE.Value = TBL24HTIDELEVEL.TLSECONDTIMELOWTIDE;
        TLLOWTIDELEVELFORTHESECONDTIME.Value = TBL24HTIDELEVEL.TLLOWTIDELEVELFORTHESECONDTIME;
        TLFORECASTSTANCE.Value = TBL24HTIDELEVEL.TLFORECASTSTANCE;
        FORECASTDATE.Value = TBL24HTIDELEVEL.FORECASTDATE.ToString();
        TLFIRSTWAVEOFTIME.Value = TBL24HTIDELEVEL.TLFIRSTWAVEOFTIME;
        TLFIRSTWAVETIDELEVEL.Value = TBL24HTIDELEVEL.TLFIRSTWAVETIDELEVEL;
        TLFIRSTTIMELOWTIDE.Value = TBL24HTIDELEVEL.TLFIRSTTIMELOWTIDE;
        TLLOWTIDELEVELFORTHEFIRSTTIME.Value = TBL24HTIDELEVEL.TLLOWTIDELEVELFORTHEFIRSTTIME;
        TLSECONDWAVEOFTIME.Value = TBL24HTIDELEVEL.TLSECONDWAVEOFTIME;
        TLSECONDWAVETIDELEVEL.Value = TBL24HTIDELEVEL.TLSECONDWAVETIDELEVEL;


        DbParameter[] parameters = { PUBLISHDATE, TLSECONDTIMELOWTIDE, TLLOWTIDELEVELFORTHESECONDTIME, TLFORECASTSTANCE, FORECASTDATE, TLFIRSTWAVEOFTIME, TLFIRSTWAVETIDELEVEL, TLFIRSTTIMELOWTIDE, TLLOWTIDELEVELFORTHEFIRSTTIME, TLSECONDWAVEOFTIME, TLSECONDWAVETIDELEVEL };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

