
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 潍坊项24小时潮汐预报
/// </summary>
/// <returns></returns>
public class sql_TBLWF24HTIDALFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLWF24HTIDALFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有潍坊项24小时潮汐预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLWF24HTIDALFORECAST_AllData(TBLWF24HTIDALFORECAST TBLWF24HTIDALFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLWF24HTIDALFORECAST where PUBLISHDATE=to_date('" + TBLWF24HTIDALFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");
          
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取潍坊项24小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增潍坊项24小时潮汐预报预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLWF24HTIDALFORECAST(TBLWF24HTIDALFORECAST TBLWF24HTIDALFORECAST)
    {

        string sql = "INSERT INTO  TBLWF24HTIDALFORECAST (PUBLISHDATE,WF24HTFFIRSTHIGHWAVETIME,WF24HTFFIRSTHIGHWAVEHEIGHT,WF24HTFSECONDHIGHWAVETIME,WF24HTFSECONDHIGHWAVEHEIGHT,WF24HTFFIRSTLOWWAVETIME,WF24HTFFIRSTLOWWAVEHEIGHT,WF24HTFSECONDLOWWAVETIME,WF24HTFSECONDLOWWAVEHEIGHT) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@WF24HTFFIRSTHIGHWAVETIME,@WF24HTFFIRSTHIGHWAVEHEIGHT,@WF24HTFSECONDHIGHWAVETIME,@WF24HTFSECONDHIGHWAVEHEIGHT,@WF24HTFFIRSTLOWWAVETIME,@WF24HTFFIRSTLOWWAVEHEIGHT,@WF24HTFSECONDLOWWAVETIME,@WF24HTFSECONDLOWWAVEHEIGHT)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var WF24HTFFIRSTHIGHWAVETIME = DataExe.GetDbParameter();
        var WF24HTFFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFSECONDHIGHWAVETIME = DataExe.GetDbParameter();
        var WF24HTFSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFFIRSTLOWWAVETIME = DataExe.GetDbParameter();
        var WF24HTFFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFSECONDLOWWAVETIME = DataExe.GetDbParameter();
        var WF24HTFSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        WF24HTFFIRSTHIGHWAVETIME.ParameterName = "@WF24HTFFIRSTHIGHWAVETIME";
        WF24HTFFIRSTHIGHWAVEHEIGHT.ParameterName = "@WF24HTFFIRSTHIGHWAVEHEIGHT";
        WF24HTFSECONDHIGHWAVETIME.ParameterName = "@WF24HTFSECONDHIGHWAVETIME";
        WF24HTFSECONDHIGHWAVEHEIGHT.ParameterName = "@WF24HTFSECONDHIGHWAVEHEIGHT";
        WF24HTFFIRSTLOWWAVETIME.ParameterName = "@WF24HTFFIRSTLOWWAVETIME";
        WF24HTFFIRSTLOWWAVEHEIGHT.ParameterName = "@WF24HTFFIRSTLOWWAVEHEIGHT";
        WF24HTFSECONDLOWWAVETIME.ParameterName = "@WF24HTFSECONDLOWWAVETIME";
        WF24HTFSECONDLOWWAVEHEIGHT.ParameterName = "@WF24HTFSECONDLOWWAVEHEIGHT";




        PUBLISHDATE.Value = TBLWF24HTIDALFORECAST.PUBLISHDATE.ToString();
        WF24HTFFIRSTHIGHWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTHIGHWAVETIME;
        WF24HTFFIRSTHIGHWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTHIGHWAVEHEIGHT;
        WF24HTFSECONDHIGHWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDHIGHWAVETIME;
        WF24HTFSECONDHIGHWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDHIGHWAVEHEIGHT;
        WF24HTFFIRSTLOWWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTLOWWAVETIME;
        WF24HTFFIRSTLOWWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTLOWWAVEHEIGHT;
        WF24HTFSECONDLOWWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDLOWWAVETIME;
        WF24HTFSECONDLOWWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDLOWWAVEHEIGHT;


        DbParameter[] parameters = { PUBLISHDATE, WF24HTFFIRSTHIGHWAVETIME, WF24HTFFIRSTHIGHWAVEHEIGHT, WF24HTFSECONDHIGHWAVETIME, WF24HTFSECONDHIGHWAVEHEIGHT, WF24HTFFIRSTLOWWAVETIME, WF24HTFFIRSTLOWWAVEHEIGHT, WF24HTFSECONDLOWWAVETIME, WF24HTFSECONDLOWWAVEHEIGHT };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增潍坊项24小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改潍坊项24小时潮汐预报预报
    /// </summary>
    public int Edit_TBLWF24HTIDALFORECAST(TBLWF24HTIDALFORECAST TBLWF24HTIDALFORECAST)
    {
        string sql = "UPDATE   TBLWF24HTIDALFORECAST set	WF24HTFFIRSTHIGHWAVETIME=@WF24HTFFIRSTHIGHWAVETIME,WF24HTFFIRSTHIGHWAVEHEIGHT=@WF24HTFFIRSTHIGHWAVEHEIGHT,WF24HTFSECONDHIGHWAVETIME=@WF24HTFSECONDHIGHWAVETIME,WF24HTFSECONDHIGHWAVEHEIGHT=@WF24HTFSECONDHIGHWAVEHEIGHT,WF24HTFFIRSTLOWWAVETIME=@WF24HTFFIRSTLOWWAVETIME,WF24HTFFIRSTLOWWAVEHEIGHT=@WF24HTFFIRSTLOWWAVEHEIGHT,WF24HTFSECONDLOWWAVETIME=@WF24HTFSECONDLOWWAVETIME,WF24HTFSECONDLOWWAVEHEIGHT=@WF24HTFSECONDLOWWAVEHEIGHT where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var WF24HTFFIRSTHIGHWAVETIME = DataExe.GetDbParameter();
        var WF24HTFFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFSECONDHIGHWAVETIME = DataExe.GetDbParameter();
        var WF24HTFSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFFIRSTLOWWAVETIME = DataExe.GetDbParameter();
        var WF24HTFFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var WF24HTFSECONDLOWWAVETIME = DataExe.GetDbParameter();
        var WF24HTFSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        WF24HTFFIRSTHIGHWAVETIME.ParameterName = "@WF24HTFFIRSTHIGHWAVETIME";
        WF24HTFFIRSTHIGHWAVEHEIGHT.ParameterName = "@WF24HTFFIRSTHIGHWAVEHEIGHT";
        WF24HTFSECONDHIGHWAVETIME.ParameterName = "@WF24HTFSECONDHIGHWAVETIME";
        WF24HTFSECONDHIGHWAVEHEIGHT.ParameterName = "@WF24HTFSECONDHIGHWAVEHEIGHT";
        WF24HTFFIRSTLOWWAVETIME.ParameterName = "@WF24HTFFIRSTLOWWAVETIME";
        WF24HTFFIRSTLOWWAVEHEIGHT.ParameterName = "@WF24HTFFIRSTLOWWAVEHEIGHT";
        WF24HTFSECONDLOWWAVETIME.ParameterName = "@WF24HTFSECONDLOWWAVETIME";
        WF24HTFSECONDLOWWAVEHEIGHT.ParameterName = "@WF24HTFSECONDLOWWAVEHEIGHT";




        PUBLISHDATE.Value = TBLWF24HTIDALFORECAST.PUBLISHDATE.ToString(); ;
        WF24HTFFIRSTHIGHWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTHIGHWAVETIME;
        WF24HTFFIRSTHIGHWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTHIGHWAVEHEIGHT;
        WF24HTFSECONDHIGHWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDHIGHWAVETIME;
        WF24HTFSECONDHIGHWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDHIGHWAVEHEIGHT;
        WF24HTFFIRSTLOWWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTLOWWAVETIME;
        WF24HTFFIRSTLOWWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFFIRSTLOWWAVEHEIGHT;
        WF24HTFSECONDLOWWAVETIME.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDLOWWAVETIME;
        WF24HTFSECONDLOWWAVEHEIGHT.Value = TBLWF24HTIDALFORECAST.WF24HTFSECONDLOWWAVEHEIGHT;


        DbParameter[] parameters = { PUBLISHDATE, WF24HTFFIRSTHIGHWAVETIME, WF24HTFFIRSTHIGHWAVEHEIGHT, WF24HTFSECONDHIGHWAVETIME, WF24HTFSECONDHIGHWAVEHEIGHT, WF24HTFFIRSTLOWWAVETIME, WF24HTFFIRSTLOWWAVEHEIGHT, WF24HTFSECONDLOWWAVETIME, WF24HTFSECONDLOWWAVEHEIGHT };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改潍坊项24小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

