
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 预计未来24小时海浪水温
/// </summary>
/// <returns></returns>
public class sql_TBLEXPECTEDFUTURE24HWAVEWATER
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLEXPECTEDFUTURE24HWAVEWATER()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有预计未来24小时海浪水温预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLEXPECTEDFUTURE24HWAVEWATER_AllData(TBLEXPECTEDFUTURE24HWAVEWATER TBLEXPECTEDFUTURE24HWAVEWATER)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLEXPECTEDFUTURE24HWAVEWATER where PUBLISHDATE=to_date('" + TBLEXPECTEDFUTURE24HWAVEWATER.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取预计未来24小时海浪水温出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增预计未来24小时海浪水温预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    /// <returns></returns>
    public int Add_TBLEXPECTEDFUTURE24HWAVEWATER(TBLEXPECTEDFUTURE24HWAVEWATER TBLEXPECTEDFUTURE24HWAVEWATER, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "sw")
        {
            sql = @"INSERT INTO  TBLEXPECTEDFUTURE24HWAVEWATER (PUBLISHDATE,EFWWHHKSEAAREAWATERTEMP,EFWWGLGSEAAREAWATERTEMP,EFWWDYGWATERTEMPERATURE,EFWWXHWATERTEMPERATURE,EFWWCKWATERTEMPERATURE,EFWWDKSEAAREAWATERTEMPE)
                VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@EFWWHHKSEAAREAWATERTEMP,@EFWWGLGSEAAREAWATERTEMP,@EFWWDYGWATERTEMPERATURE,@EFWWXHWATERTEMPERATURE,@EFWWCKWATERTEMPERATURE,@EFWWDKSEAAREAWATERTEMPE)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            //var EFWWHHKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWHHKSEAAREAWATERTEMP = DataExe.GetDbParameter();
            //var EFWWGLGSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWGLGSEAAREAWATERTEMP = DataExe.GetDbParameter();
            //var EFWWDYGWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWDYGWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWXHWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWXHWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWCKWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWCKWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWBHLOWESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHHIGHESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHWAVETYPE = DataExe.GetDbParameter();
            //var EFWWBHNORTHLOWESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHNORTHHIGHESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHNORTHWAVETYPE = DataExe.GetDbParameter();
            //var EFWWDKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWDKSEAAREAWATERTEMPE = DataExe.GetDbParameter();




            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            //EFWWHHKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWHHKSEAAREAWAVEHEIGHT";
            EFWWHHKSEAAREAWATERTEMP.ParameterName = "@EFWWHHKSEAAREAWATERTEMP";
            //EFWWGLGSEAAREAWAVEHEIGHT.ParameterName = "@EFWWGLGSEAAREAWAVEHEIGHT";
            EFWWGLGSEAAREAWATERTEMP.ParameterName = "@EFWWGLGSEAAREAWATERTEMP";
            //EFWWDYGWAVEHEIGHT.ParameterName = "@EFWWDYGWAVEHEIGHT";
            EFWWDYGWATERTEMPERATURE.ParameterName = "@EFWWDYGWATERTEMPERATURE";
            //EFWWXHWAVEHEIGHT.ParameterName = "@EFWWXHWAVEHEIGHT";
            EFWWXHWATERTEMPERATURE.ParameterName = "@EFWWXHWATERTEMPERATURE";
            //EFWWCKWAVEHEIGHT.ParameterName = "@EFWWCKWAVEHEIGHT";
            EFWWCKWATERTEMPERATURE.ParameterName = "@EFWWCKWATERTEMPERATURE";
            //EFWWBHLOWESTWAVE.ParameterName = "@EFWWBHLOWESTWAVE";
            //EFWWBHHIGHESTWAVE.ParameterName = "@EFWWBHHIGHESTWAVE";
            //EFWWBHWAVETYPE.ParameterName = "@EFWWBHWAVETYPE";
            //EFWWBHNORTHLOWESTWAVE.ParameterName = "@EFWWBHNORTHLOWESTWAVE";
            //EFWWBHNORTHHIGHESTWAVE.ParameterName = "@EFWWBHNORTHHIGHESTWAVE";
            //EFWWBHNORTHWAVETYPE.ParameterName = "@EFWWBHNORTHWAVETYPE";
            //EFWWDKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWDKSEAAREAWAVEHEIGHT";
            EFWWDKSEAAREAWATERTEMPE.ParameterName = "@EFWWDKSEAAREAWATERTEMPE";




            PUBLISHDATE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.PUBLISHDATE.ToString();
            //EFWWHHKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWAVEHEIGHT;
            EFWWHHKSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWATERTEMP;
            //EFWWGLGSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWAVEHEIGHT;
            EFWWGLGSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWATERTEMP;
            //EFWWDYGWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWAVEHEIGHT;
            EFWWDYGWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWATERTEMPERATURE;
            //EFWWXHWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWAVEHEIGHT;
            EFWWXHWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWATERTEMPERATURE;
            //EFWWCKWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWAVEHEIGHT;
            EFWWCKWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWATERTEMPERATURE;
            //EFWWBHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHLOWESTWAVE;
            //EFWWBHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHHIGHESTWAVE;
            //EFWWBHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHWAVETYPE;
            //EFWWBHNORTHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHLOWESTWAVE;
            //EFWWBHNORTHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHHIGHESTWAVE;
            //EFWWBHNORTHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHWAVETYPE;
            //EFWWDKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWAVEHEIGHT;
            EFWWDKSEAAREAWATERTEMPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWATERTEMPE;


            parameters = new DbParameter[] { PUBLISHDATE, EFWWHHKSEAAREAWATERTEMP, EFWWGLGSEAAREAWATERTEMP, EFWWDYGWATERTEMPERATURE, EFWWXHWATERTEMPERATURE, EFWWCKWATERTEMPERATURE, EFWWDKSEAAREAWATERTEMPE };
        }
        else if (quanxian.ToLower() == "fl")
        {
            sql = "INSERT INTO  TBLEXPECTEDFUTURE24HWAVEWATER (PUBLISHDATE,EFWWHHKSEAAREAWAVEHEIGHT,EFWWGLGSEAAREAWAVEHEIGHT,EFWWDYGWAVEHEIGHT,EFWWXHWAVEHEIGHT,EFWWCKWAVEHEIGHT,EFWWBHLOWESTWAVE,EFWWBHHIGHESTWAVE,EFWWBHWAVETYPE,EFWWBHNORTHLOWESTWAVE,EFWWBHNORTHHIGHESTWAVE,EFWWBHNORTHWAVETYPE,EFWWDKSEAAREAWAVEHEIGHT) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@EFWWHHKSEAAREAWAVEHEIGHT,@EFWWGLGSEAAREAWAVEHEIGHT,@EFWWDYGWAVEHEIGHT,@EFWWXHWAVEHEIGHT,@EFWWCKWAVEHEIGHT,@EFWWBHLOWESTWAVE,@EFWWBHHIGHESTWAVE,@EFWWBHWAVETYPE,@EFWWBHNORTHLOWESTWAVE,@EFWWBHNORTHHIGHESTWAVE,@EFWWBHNORTHWAVETYPE,@EFWWDKSEAAREAWAVEHEIGHT)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var EFWWHHKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWHHKSEAAREAWATERTEMP = DataExe.GetDbParameter();
            var EFWWGLGSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWGLGSEAAREAWATERTEMP = DataExe.GetDbParameter();
            var EFWWDYGWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWDYGWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWXHWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWXHWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWCKWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWCKWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWBHLOWESTWAVE = DataExe.GetDbParameter();
            var EFWWBHHIGHESTWAVE = DataExe.GetDbParameter();
            var EFWWBHWAVETYPE = DataExe.GetDbParameter();
            var EFWWBHNORTHLOWESTWAVE = DataExe.GetDbParameter();
            var EFWWBHNORTHHIGHESTWAVE = DataExe.GetDbParameter();
            var EFWWBHNORTHWAVETYPE = DataExe.GetDbParameter();
            var EFWWDKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWDKSEAAREAWATERTEMPE = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            EFWWHHKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWHHKSEAAREAWAVEHEIGHT";
            //EFWWHHKSEAAREAWATERTEMP.ParameterName = "@EFWWHHKSEAAREAWATERTEMP";
            EFWWGLGSEAAREAWAVEHEIGHT.ParameterName = "@EFWWGLGSEAAREAWAVEHEIGHT";
            //EFWWGLGSEAAREAWATERTEMP.ParameterName = "@EFWWGLGSEAAREAWATERTEMP";
            EFWWDYGWAVEHEIGHT.ParameterName = "@EFWWDYGWAVEHEIGHT";
            //EFWWDYGWATERTEMPERATURE.ParameterName = "@EFWWDYGWATERTEMPERATURE";
            EFWWXHWAVEHEIGHT.ParameterName = "@EFWWXHWAVEHEIGHT";
            //EFWWXHWATERTEMPERATURE.ParameterName = "@EFWWXHWATERTEMPERATURE";
            EFWWCKWAVEHEIGHT.ParameterName = "@EFWWCKWAVEHEIGHT";
            //EFWWCKWATERTEMPERATURE.ParameterName = "@EFWWCKWATERTEMPERATURE";
            EFWWBHLOWESTWAVE.ParameterName = "@EFWWBHLOWESTWAVE";
            EFWWBHHIGHESTWAVE.ParameterName = "@EFWWBHHIGHESTWAVE";
            EFWWBHWAVETYPE.ParameterName = "@EFWWBHWAVETYPE";
            EFWWBHNORTHLOWESTWAVE.ParameterName = "@EFWWBHNORTHLOWESTWAVE";
            EFWWBHNORTHHIGHESTWAVE.ParameterName = "@EFWWBHNORTHHIGHESTWAVE";
            EFWWBHNORTHWAVETYPE.ParameterName = "@EFWWBHNORTHWAVETYPE";
            EFWWDKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWDKSEAAREAWAVEHEIGHT";
            //EFWWDKSEAAREAWATERTEMPE.ParameterName = "@EFWWDKSEAAREAWATERTEMPE";

            PUBLISHDATE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.PUBLISHDATE.ToString();
            EFWWHHKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWAVEHEIGHT;
            //EFWWHHKSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWATERTEMP;
            EFWWGLGSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWAVEHEIGHT;
            //EFWWGLGSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWATERTEMP;
            EFWWDYGWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWAVEHEIGHT;
            //EFWWDYGWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWATERTEMPERATURE;
            EFWWXHWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWAVEHEIGHT;
            //EFWWXHWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWATERTEMPERATURE;
            EFWWCKWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWAVEHEIGHT;
            //EFWWCKWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWATERTEMPERATURE;
            EFWWBHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHLOWESTWAVE;
            EFWWBHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHHIGHESTWAVE;
            EFWWBHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHWAVETYPE;
            EFWWBHNORTHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHLOWESTWAVE;
            EFWWBHNORTHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHHIGHESTWAVE;
            EFWWBHNORTHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHWAVETYPE;
            EFWWDKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWAVEHEIGHT;
            //EFWWDKSEAAREAWATERTEMPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWATERTEMPE;


            parameters = new DbParameter[] { PUBLISHDATE, EFWWHHKSEAAREAWAVEHEIGHT, EFWWGLGSEAAREAWAVEHEIGHT, EFWWDYGWAVEHEIGHT, EFWWXHWAVEHEIGHT, EFWWCKWAVEHEIGHT, EFWWBHLOWESTWAVE, EFWWBHHIGHESTWAVE, EFWWBHWAVETYPE, EFWWBHNORTHLOWESTWAVE, EFWWBHNORTHHIGHESTWAVE, EFWWBHNORTHWAVETYPE, EFWWDKSEAAREAWAVEHEIGHT };
        }
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增预计未来24小时海浪水温出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改预计未来24小时海浪水温预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    public int Edit_TBLEXPECTEDFUTURE24HWAVEWATER(TBLEXPECTEDFUTURE24HWAVEWATER TBLEXPECTEDFUTURE24HWAVEWATER, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "sw")
        {
            sql = "UPDATE   TBLEXPECTEDFUTURE24HWAVEWATER set	EFWWHHKSEAAREAWATERTEMP=@EFWWHHKSEAAREAWATERTEMP,EFWWGLGSEAAREAWATERTEMP=@EFWWGLGSEAAREAWATERTEMP,EFWWDYGWATERTEMPERATURE=@EFWWDYGWATERTEMPERATURE,EFWWXHWATERTEMPERATURE=@EFWWXHWATERTEMPERATURE,EFWWCKWATERTEMPERATURE=@EFWWCKWATERTEMPERATURE,EFWWDKSEAAREAWATERTEMPE=@EFWWDKSEAAREAWATERTEMPE where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            //var EFWWHHKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWHHKSEAAREAWATERTEMP = DataExe.GetDbParameter();
            //var EFWWGLGSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWGLGSEAAREAWATERTEMP = DataExe.GetDbParameter();
            //var EFWWDYGWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWDYGWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWXHWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWXHWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWCKWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWCKWATERTEMPERATURE = DataExe.GetDbParameter();
            //var EFWWBHLOWESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHHIGHESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHWAVETYPE = DataExe.GetDbParameter();
            //var EFWWBHNORTHLOWESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHNORTHHIGHESTWAVE = DataExe.GetDbParameter();
            //var EFWWBHNORTHWAVETYPE = DataExe.GetDbParameter();
            //var EFWWDKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            var EFWWDKSEAAREAWATERTEMPE = DataExe.GetDbParameter();
            
            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            //EFWWHHKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWHHKSEAAREAWAVEHEIGHT";
            EFWWHHKSEAAREAWATERTEMP.ParameterName = "@EFWWHHKSEAAREAWATERTEMP";
            //EFWWGLGSEAAREAWAVEHEIGHT.ParameterName = "@EFWWGLGSEAAREAWAVEHEIGHT";
            EFWWGLGSEAAREAWATERTEMP.ParameterName = "@EFWWGLGSEAAREAWATERTEMP";
            //EFWWDYGWAVEHEIGHT.ParameterName = "@EFWWDYGWAVEHEIGHT";
            EFWWDYGWATERTEMPERATURE.ParameterName = "@EFWWDYGWATERTEMPERATURE";
            //EFWWXHWAVEHEIGHT.ParameterName = "@EFWWXHWAVEHEIGHT";
            EFWWXHWATERTEMPERATURE.ParameterName = "@EFWWXHWATERTEMPERATURE";
            //EFWWCKWAVEHEIGHT.ParameterName = "@EFWWCKWAVEHEIGHT";
            EFWWCKWATERTEMPERATURE.ParameterName = "@EFWWCKWATERTEMPERATURE";
            //EFWWBHLOWESTWAVE.ParameterName = "@EFWWBHLOWESTWAVE";
            //EFWWBHHIGHESTWAVE.ParameterName = "@EFWWBHHIGHESTWAVE";
            //EFWWBHWAVETYPE.ParameterName = "@EFWWBHWAVETYPE";
            //EFWWBHNORTHLOWESTWAVE.ParameterName = "@EFWWBHNORTHLOWESTWAVE";
            //EFWWBHNORTHHIGHESTWAVE.ParameterName = "@EFWWBHNORTHHIGHESTWAVE";
            //EFWWBHNORTHWAVETYPE.ParameterName = "@EFWWBHNORTHWAVETYPE";
            //EFWWDKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWDKSEAAREAWAVEHEIGHT";
            EFWWDKSEAAREAWATERTEMPE.ParameterName = "@EFWWDKSEAAREAWATERTEMPE";
            
            PUBLISHDATE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.PUBLISHDATE.ToString(); ;
            //EFWWHHKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWAVEHEIGHT;
            EFWWHHKSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWATERTEMP;
            //EFWWGLGSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWAVEHEIGHT;
            EFWWGLGSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWATERTEMP;
            //EFWWDYGWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWAVEHEIGHT;
            EFWWDYGWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWATERTEMPERATURE;
            //EFWWXHWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWAVEHEIGHT;
            EFWWXHWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWATERTEMPERATURE;
            //EFWWCKWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWAVEHEIGHT;
            EFWWCKWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWATERTEMPERATURE;
            //EFWWBHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHLOWESTWAVE;
            //EFWWBHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHHIGHESTWAVE;
            //EFWWBHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHWAVETYPE;
            //EFWWBHNORTHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHLOWESTWAVE;
            //EFWWBHNORTHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHHIGHESTWAVE;
            //EFWWBHNORTHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHWAVETYPE;
            //EFWWDKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWAVEHEIGHT;
            EFWWDKSEAAREAWATERTEMPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWATERTEMPE;

            parameters = new DbParameter[] { PUBLISHDATE, EFWWHHKSEAAREAWATERTEMP, EFWWGLGSEAAREAWATERTEMP, EFWWDYGWATERTEMPERATURE, EFWWXHWATERTEMPERATURE, EFWWCKWATERTEMPERATURE, EFWWDKSEAAREAWATERTEMPE };
        }
        else if (quanxian.ToLower() == "fl")
        {
            sql = "UPDATE   TBLEXPECTEDFUTURE24HWAVEWATER set	EFWWHHKSEAAREAWAVEHEIGHT=@EFWWHHKSEAAREAWAVEHEIGHT,EFWWGLGSEAAREAWAVEHEIGHT=@EFWWGLGSEAAREAWAVEHEIGHT,EFWWDYGWAVEHEIGHT=@EFWWDYGWAVEHEIGHT,EFWWXHWAVEHEIGHT=@EFWWXHWAVEHEIGHT,EFWWCKWAVEHEIGHT=@EFWWCKWAVEHEIGHT,EFWWBHLOWESTWAVE=@EFWWBHLOWESTWAVE,EFWWBHHIGHESTWAVE=@EFWWBHHIGHESTWAVE,EFWWBHWAVETYPE=@EFWWBHWAVETYPE,EFWWBHNORTHLOWESTWAVE=@EFWWBHNORTHLOWESTWAVE,EFWWBHNORTHHIGHESTWAVE=@EFWWBHNORTHHIGHESTWAVE,EFWWBHNORTHWAVETYPE=@EFWWBHNORTHWAVETYPE,EFWWDKSEAAREAWAVEHEIGHT=@EFWWDKSEAAREAWAVEHEIGHT where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


            var PUBLISHDATE = DataExe.GetDbParameter();
            var EFWWHHKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWHHKSEAAREAWATERTEMP = DataExe.GetDbParameter();
            var EFWWGLGSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWGLGSEAAREAWATERTEMP = DataExe.GetDbParameter();
            var EFWWDYGWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWDYGWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWXHWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWXHWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWCKWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWCKWATERTEMPERATURE = DataExe.GetDbParameter();
            var EFWWBHLOWESTWAVE = DataExe.GetDbParameter();
            var EFWWBHHIGHESTWAVE = DataExe.GetDbParameter();
            var EFWWBHWAVETYPE = DataExe.GetDbParameter();
            var EFWWBHNORTHLOWESTWAVE = DataExe.GetDbParameter();
            var EFWWBHNORTHHIGHESTWAVE = DataExe.GetDbParameter();
            var EFWWBHNORTHWAVETYPE = DataExe.GetDbParameter();
            var EFWWDKSEAAREAWAVEHEIGHT = DataExe.GetDbParameter();
            //var EFWWDKSEAAREAWATERTEMPE = DataExe.GetDbParameter();




            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            EFWWHHKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWHHKSEAAREAWAVEHEIGHT";
            //EFWWHHKSEAAREAWATERTEMP.ParameterName = "@EFWWHHKSEAAREAWATERTEMP";
            EFWWGLGSEAAREAWAVEHEIGHT.ParameterName = "@EFWWGLGSEAAREAWAVEHEIGHT";
            //EFWWGLGSEAAREAWATERTEMP.ParameterName = "@EFWWGLGSEAAREAWATERTEMP";
            EFWWDYGWAVEHEIGHT.ParameterName = "@EFWWDYGWAVEHEIGHT";
            //EFWWDYGWATERTEMPERATURE.ParameterName = "@EFWWDYGWATERTEMPERATURE";
            EFWWXHWAVEHEIGHT.ParameterName = "@EFWWXHWAVEHEIGHT";
            //EFWWXHWATERTEMPERATURE.ParameterName = "@EFWWXHWATERTEMPERATURE";
            EFWWCKWAVEHEIGHT.ParameterName = "@EFWWCKWAVEHEIGHT";
            //EFWWCKWATERTEMPERATURE.ParameterName = "@EFWWCKWATERTEMPERATURE";
            EFWWBHLOWESTWAVE.ParameterName = "@EFWWBHLOWESTWAVE";
            EFWWBHHIGHESTWAVE.ParameterName = "@EFWWBHHIGHESTWAVE";
            EFWWBHWAVETYPE.ParameterName = "@EFWWBHWAVETYPE";
            EFWWBHNORTHLOWESTWAVE.ParameterName = "@EFWWBHNORTHLOWESTWAVE";
            EFWWBHNORTHHIGHESTWAVE.ParameterName = "@EFWWBHNORTHHIGHESTWAVE";
            EFWWBHNORTHWAVETYPE.ParameterName = "@EFWWBHNORTHWAVETYPE";
            EFWWDKSEAAREAWAVEHEIGHT.ParameterName = "@EFWWDKSEAAREAWAVEHEIGHT";
            //EFWWDKSEAAREAWATERTEMPE.ParameterName = "@EFWWDKSEAAREAWATERTEMPE";




            PUBLISHDATE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.PUBLISHDATE.ToString(); ;
            EFWWHHKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWAVEHEIGHT;
            //EFWWHHKSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWHHKSEAAREAWATERTEMP;
            EFWWGLGSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWAVEHEIGHT;
            //EFWWGLGSEAAREAWATERTEMP.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWGLGSEAAREAWATERTEMP;
            EFWWDYGWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWAVEHEIGHT;
            //EFWWDYGWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDYGWATERTEMPERATURE;
            EFWWXHWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWAVEHEIGHT;
            //EFWWXHWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWXHWATERTEMPERATURE;
            EFWWCKWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWAVEHEIGHT;
            //EFWWCKWATERTEMPERATURE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWCKWATERTEMPERATURE;
            EFWWBHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHLOWESTWAVE;
            EFWWBHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHHIGHESTWAVE;
            EFWWBHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHWAVETYPE;
            EFWWBHNORTHLOWESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHLOWESTWAVE;
            EFWWBHNORTHHIGHESTWAVE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHHIGHESTWAVE;
            EFWWBHNORTHWAVETYPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWBHNORTHWAVETYPE;
            EFWWDKSEAAREAWAVEHEIGHT.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWAVEHEIGHT;
            //EFWWDKSEAAREAWATERTEMPE.Value = TBLEXPECTEDFUTURE24HWAVEWATER.EFWWDKSEAAREAWATERTEMPE;


            parameters = new DbParameter[] { PUBLISHDATE, EFWWHHKSEAAREAWAVEHEIGHT,  EFWWGLGSEAAREAWAVEHEIGHT,  EFWWDYGWAVEHEIGHT,  EFWWXHWAVEHEIGHT,  EFWWCKWAVEHEIGHT,  EFWWBHLOWESTWAVE, EFWWBHHIGHESTWAVE, EFWWBHWAVETYPE, EFWWBHNORTHLOWESTWAVE, EFWWBHNORTHHIGHESTWAVE, EFWWBHNORTHWAVETYPE, EFWWDKSEAAREAWAVEHEIGHT };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改预计未来24小时海浪水温出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

