
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 各海区24小时海浪预报
/// </summary>
/// <returns></returns>
public class sql_TBLSEABEACH24HWAVEFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLSEABEACH24HWAVEFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有各海区24小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLSEABEACH24HWAVEFORECAST_AllData(TBLSEABEACH24HWAVEFORECAST TBLSEABEACH24HWAVEFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLSEABEACH24HWAVEFORECAST where PUBLISHDATE=to_date('" + TBLSEABEACH24HWAVEFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取各海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增各海区24小时海浪预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    /// <returns></returns>
    public int Add_TBLSEABEACH24HWAVEFORECAST(TBLSEABEACH24HWAVEFORECAST TBLSEABEACH24HWAVEFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "INSERT INTO  TBLSEABEACH24HWAVEFORECAST (PUBLISHDATE,SB24HWFSLRBATHINGSWIMWARN,SB24HWFGOLDBEACHWAVEHEIGHT,SB24HWFGOLDBEACHSWIMWAIN,SB24HWFFIRSTBATHINGWAVEHEIGHT,SB24HWFFIRSTBATHINGSWIMWARN,SB24HWFSIXTHBATHINGWAVEHEIGHT,SB24HWFSIXTHBATHINGSWIMWARN,SB24HWFSLRBATHINGWAVEHEIGHT) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@SB24HWFSLRBATHINGSWIMWARN,@SB24HWFGOLDBEACHWAVEHEIGHT,@SB24HWFGOLDBEACHSWIMWAIN,@SB24HWFFIRSTBATHINGWAVEHEIGHT,@SB24HWFFIRSTBATHINGSWIMWARN,@SB24HWFSIXTHBATHINGWAVEHEIGHT,@SB24HWFSIXTHBATHINGSWIMWARN,@SB24HWFSLRBATHINGWAVEHEIGHT)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHSWIMWAIN = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            SB24HWFSLRBATHINGSWIMWARN.ParameterName = "@SB24HWFSLRBATHINGSWIMWARN";
            SB24HWFGOLDBEACHWAVEHEIGHT.ParameterName = "@SB24HWFGOLDBEACHWAVEHEIGHT";
            SB24HWFGOLDBEACHSWIMWAIN.ParameterName = "@SB24HWFGOLDBEACHSWIMWAIN";
            SB24HWFFIRSTBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFFIRSTBATHINGWAVEHEIGHT";
            SB24HWFFIRSTBATHINGSWIMWARN.ParameterName = "@SB24HWFFIRSTBATHINGSWIMWARN";
            SB24HWFSIXTHBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFSIXTHBATHINGWAVEHEIGHT";
            SB24HWFSIXTHBATHINGSWIMWARN.ParameterName = "@SB24HWFSIXTHBATHINGSWIMWARN";
            SB24HWFSLRBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFSLRBATHINGWAVEHEIGHT";




            PUBLISHDATE.Value = TBLSEABEACH24HWAVEFORECAST.PUBLISHDATE.ToString();
            SB24HWFSLRBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGSWIMWARN;
            SB24HWFGOLDBEACHWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHWAVEHEIGHT;
            SB24HWFGOLDBEACHSWIMWAIN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHSWIMWAIN;
            SB24HWFFIRSTBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGWAVEHEIGHT;
            SB24HWFFIRSTBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGSWIMWARN;
            SB24HWFSIXTHBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGWAVEHEIGHT;
            SB24HWFSIXTHBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGSWIMWARN;
            SB24HWFSLRBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGWAVEHEIGHT;


            parameters = new DbParameter[] { PUBLISHDATE, SB24HWFSLRBATHINGSWIMWARN, SB24HWFGOLDBEACHWAVEHEIGHT, SB24HWFGOLDBEACHSWIMWAIN, SB24HWFFIRSTBATHINGWAVEHEIGHT, SB24HWFFIRSTBATHINGSWIMWARN, SB24HWFSIXTHBATHINGWAVEHEIGHT, SB24HWFSIXTHBATHINGSWIMWARN, SB24HWFSLRBATHINGWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {
            sql = "INSERT INTO  TBLSEABEACH24HWAVEFORECAST (PUBLISHDATE,SB24HWFGOLDBEACHWATERTEMP,SB24HWFFIRSTBATHINGWATERTEMP,SB24HWFSIXTHBATHINGWATERTEMP,SB24HWFSLRBATHINGWATERTEMP) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@SB24HWFGOLDBEACHWATERTEMP,@SB24HWFFIRSTBATHINGWATERTEMP,@SB24HWFSIXTHBATHINGWATERTEMP,@SB24HWFSLRBATHINGWATERTEMP)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGWATERTEMP = DataExe.GetDbParameter();




            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            SB24HWFGOLDBEACHWATERTEMP.ParameterName = "@SB24HWFGOLDBEACHWATERTEMP";
            SB24HWFFIRSTBATHINGWATERTEMP.ParameterName = "@SB24HWFFIRSTBATHINGWATERTEMP";
            SB24HWFSIXTHBATHINGWATERTEMP.ParameterName = "@SB24HWFSIXTHBATHINGWATERTEMP";
            SB24HWFSLRBATHINGWATERTEMP.ParameterName = "@SB24HWFSLRBATHINGWATERTEMP";




            PUBLISHDATE.Value = TBLSEABEACH24HWAVEFORECAST.PUBLISHDATE.ToString();
            SB24HWFGOLDBEACHWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHWATERTEMP;
            SB24HWFFIRSTBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGWATERTEMP;
            SB24HWFSIXTHBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGWATERTEMP;
            SB24HWFSLRBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGWATERTEMP;


            parameters = new DbParameter[] { PUBLISHDATE, SB24HWFGOLDBEACHWATERTEMP, SB24HWFFIRSTBATHINGWATERTEMP, SB24HWFSIXTHBATHINGWATERTEMP, SB24HWFSLRBATHINGWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增各海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改各海区24小时海浪预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    public int Edit_TBLSEABEACH24HWAVEFORECAST(TBLSEABEACH24HWAVEFORECAST TBLSEABEACH24HWAVEFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "UPDATE   TBLSEABEACH24HWAVEFORECAST set	SB24HWFSLRBATHINGSWIMWARN=@SB24HWFSLRBATHINGSWIMWARN,SB24HWFGOLDBEACHWAVEHEIGHT=@SB24HWFGOLDBEACHWAVEHEIGHT,SB24HWFGOLDBEACHSWIMWAIN=@SB24HWFGOLDBEACHSWIMWAIN,SB24HWFFIRSTBATHINGWAVEHEIGHT=@SB24HWFFIRSTBATHINGWAVEHEIGHT,SB24HWFFIRSTBATHINGSWIMWARN=@SB24HWFFIRSTBATHINGSWIMWARN,SB24HWFSIXTHBATHINGWAVEHEIGHT=@SB24HWFSIXTHBATHINGWAVEHEIGHT,SB24HWFSIXTHBATHINGSWIMWARN=@SB24HWFSIXTHBATHINGSWIMWARN,SB24HWFSLRBATHINGWAVEHEIGHT=@SB24HWFSLRBATHINGWAVEHEIGHT where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHSWIMWAIN = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGWAVEHEIGHT = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGSWIMWARN = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            SB24HWFSLRBATHINGSWIMWARN.ParameterName = "@SB24HWFSLRBATHINGSWIMWARN";
            SB24HWFGOLDBEACHWAVEHEIGHT.ParameterName = "@SB24HWFGOLDBEACHWAVEHEIGHT";
            SB24HWFGOLDBEACHSWIMWAIN.ParameterName = "@SB24HWFGOLDBEACHSWIMWAIN";
            SB24HWFFIRSTBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFFIRSTBATHINGWAVEHEIGHT";
            SB24HWFFIRSTBATHINGSWIMWARN.ParameterName = "@SB24HWFFIRSTBATHINGSWIMWARN";
            SB24HWFSIXTHBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFSIXTHBATHINGWAVEHEIGHT";
            SB24HWFSIXTHBATHINGSWIMWARN.ParameterName = "@SB24HWFSIXTHBATHINGSWIMWARN";
            SB24HWFSLRBATHINGWAVEHEIGHT.ParameterName = "@SB24HWFSLRBATHINGWAVEHEIGHT";

            PUBLISHDATE.Value = TBLSEABEACH24HWAVEFORECAST.PUBLISHDATE.ToString();
            SB24HWFSLRBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGSWIMWARN;
            SB24HWFGOLDBEACHWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHWAVEHEIGHT;
            SB24HWFGOLDBEACHSWIMWAIN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHSWIMWAIN;
            SB24HWFFIRSTBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGWAVEHEIGHT;
            SB24HWFFIRSTBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGSWIMWARN;
            SB24HWFSIXTHBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGWAVEHEIGHT;
            SB24HWFSIXTHBATHINGSWIMWARN.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGSWIMWARN;
            SB24HWFSLRBATHINGWAVEHEIGHT.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGWAVEHEIGHT;

            parameters = new DbParameter[] { PUBLISHDATE, SB24HWFSLRBATHINGSWIMWARN, SB24HWFGOLDBEACHWAVEHEIGHT, SB24HWFGOLDBEACHSWIMWAIN, SB24HWFFIRSTBATHINGWAVEHEIGHT, SB24HWFFIRSTBATHINGSWIMWARN, SB24HWFSIXTHBATHINGWAVEHEIGHT, SB24HWFSIXTHBATHINGSWIMWARN, SB24HWFSLRBATHINGWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {
            sql = "UPDATE   TBLSEABEACH24HWAVEFORECAST set	SB24HWFGOLDBEACHWATERTEMP=@SB24HWFGOLDBEACHWATERTEMP,SB24HWFFIRSTBATHINGWATERTEMP=@SB24HWFFIRSTBATHINGWATERTEMP,SB24HWFSIXTHBATHINGWATERTEMP=@SB24HWFSIXTHBATHINGWATERTEMP,SB24HWFSLRBATHINGWATERTEMP=@SB24HWFSLRBATHINGWATERTEMP where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var SB24HWFGOLDBEACHWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFFIRSTBATHINGWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFSIXTHBATHINGWATERTEMP = DataExe.GetDbParameter();
            var SB24HWFSLRBATHINGWATERTEMP = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            SB24HWFGOLDBEACHWATERTEMP.ParameterName = "@SB24HWFGOLDBEACHWATERTEMP";
            SB24HWFFIRSTBATHINGWATERTEMP.ParameterName = "@SB24HWFFIRSTBATHINGWATERTEMP";
            SB24HWFSIXTHBATHINGWATERTEMP.ParameterName = "@SB24HWFSIXTHBATHINGWATERTEMP";
            SB24HWFSLRBATHINGWATERTEMP.ParameterName = "@SB24HWFSLRBATHINGWATERTEMP";

            PUBLISHDATE.Value = TBLSEABEACH24HWAVEFORECAST.PUBLISHDATE.ToString();
            SB24HWFGOLDBEACHWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFGOLDBEACHWATERTEMP;
            SB24HWFFIRSTBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFFIRSTBATHINGWATERTEMP;
            SB24HWFSIXTHBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSIXTHBATHINGWATERTEMP;
            SB24HWFSLRBATHINGWATERTEMP.Value = TBLSEABEACH24HWAVEFORECAST.SB24HWFSLRBATHINGWATERTEMP;

            parameters = new DbParameter[] { PUBLISHDATE, SB24HWFGOLDBEACHWATERTEMP, SB24HWFFIRSTBATHINGWATERTEMP, SB24HWFSIXTHBATHINGWATERTEMP, SB24HWFSLRBATHINGWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改各海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

