
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 海区24小时海浪预报
/// </summary>
/// <returns></returns>
public class sql_TBLSEAAREA24HWAVEFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLSEAAREA24HWAVEFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有海区24小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLSEAAREA24HWAVEFORECAST_AllData(TBLSEAAREA24HWAVEFORECAST TBLSEAAREA24HWAVEFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLSEAAREA24HWAVEFORECAST where PUBLISHDATE=to_date('" + TBLSEAAREA24HWAVEFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增海区24小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLSEAAREA24HWAVEFORECAST(TBLSEAAREA24HWAVEFORECAST TBLSEAAREA24HWAVEFORECAST)
    {

        string sql = "INSERT INTO  TBLSEAAREA24HWAVEFORECAST (PUBLISHDATE,SA24HWFMIDDLEOFYSSURGEDIR,SA24HWFSOUTHOFYSWAVEHEIGHT,"
            +"SA24HWFSOUTHOFYSWAVEDIR,SA24HWFSOUTHOFYSSURGEDIR,SA24HWFQDOFFSHOREWAVEHEIGHT,SA24HWFQDOFFSHOREWAVEDIR,"
            +"SA24HWFQDOFFSHORESURGESTATE,SA24HWFQDOFFSHORESURGEDIR,SA24HWFBOHAIWAVENOTES,SA24HWFNORTHOFYSWAVENOTES,"
            +"SA24HWFBOHAIWAVEHEIGHT,SA24HWFMIDDLEOFYSWAVENOTES,SA24HWFSOUTHOFYSWAVENOTES,SA24HWFQDOFFSHOREWAVENOTES,"
            +"SA24HWFBOHAIWAVEDIR,SA24HWFBOHAISURGEDIR,SA24HWFNORTHOFYSWAVEHEIGHT,SA24HWFNORTHOFYSWAVEDIR,"
            +"SA24HWFNORTHOFYSSURGEDIR,SA24HWFMIDDLEOFYSWAVEHEIGHT,SA24HWFMIDDLEOFYSWAVEDIR,"
            + "SA24HWFBOHAIWAVETYPE,SA24HWFNORTHOFYSWAVETYPE,SA24HWFMIDDLEOFYSWAVETYPE) VALUES"
            + "(to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@SA24HWFMIDDLEOFYSSURGEDIR,@SA24HWFSOUTHOFYSWAVEHEIGHT,"
            +"@SA24HWFSOUTHOFYSWAVEDIR,@SA24HWFSOUTHOFYSSURGEDIR,@SA24HWFQDOFFSHOREWAVEHEIGHT,@SA24HWFQDOFFSHOREWAVEDIR,"
            +"@SA24HWFQDOFFSHORESURGESTATE,@SA24HWFQDOFFSHORESURGEDIR,@SA24HWFBOHAIWAVENOTES,@SA24HWFNORTHOFYSWAVENOTES,"
            +"@SA24HWFBOHAIWAVEHEIGHT,@SA24HWFMIDDLEOFYSWAVENOTES,@SA24HWFSOUTHOFYSWAVENOTES,@SA24HWFQDOFFSHOREWAVENOTES,"
            +"@SA24HWFBOHAIWAVEDIR,@SA24HWFBOHAISURGEDIR,@SA24HWFNORTHOFYSWAVEHEIGHT,@SA24HWFNORTHOFYSWAVEDIR,"
            +"@SA24HWFNORTHOFYSSURGEDIR,@SA24HWFMIDDLEOFYSWAVEHEIGHT,@SA24HWFMIDDLEOFYSWAVEDIR,"
            + "@SA24HWFBOHAIWAVETYPE,@SA24HWFNORTHOFYSWAVETYPE,@SA24HWFMIDDLEOFYSWAVETYPE)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHORESURGESTATE = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHORESURGEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVETYPE = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVETYPE = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVETYPE = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA24HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA24HWFMIDDLEOFYSSURGEDIR";
        SA24HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA24HWFSOUTHOFYSWAVEHEIGHT";
        SA24HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA24HWFSOUTHOFYSWAVEDIR";
        SA24HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA24HWFSOUTHOFYSSURGEDIR";
        SA24HWFQDOFFSHOREWAVEHEIGHT.ParameterName = "@SA24HWFQDOFFSHOREWAVEHEIGHT";
        SA24HWFQDOFFSHOREWAVEDIR.ParameterName = "@SA24HWFQDOFFSHOREWAVEDIR";
        SA24HWFQDOFFSHORESURGESTATE.ParameterName = "@SA24HWFQDOFFSHORESURGESTATE";
        SA24HWFQDOFFSHORESURGEDIR.ParameterName = "@SA24HWFQDOFFSHORESURGEDIR";
        SA24HWFBOHAIWAVENOTES.ParameterName = "@SA24HWFBOHAIWAVENOTES";
        SA24HWFNORTHOFYSWAVENOTES.ParameterName = "@SA24HWFNORTHOFYSWAVENOTES";
        SA24HWFBOHAIWAVEHEIGHT.ParameterName = "@SA24HWFBOHAIWAVEHEIGHT";
        SA24HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA24HWFMIDDLEOFYSWAVENOTES";
        SA24HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA24HWFSOUTHOFYSWAVENOTES";
        SA24HWFQDOFFSHOREWAVENOTES.ParameterName = "@SA24HWFQDOFFSHOREWAVENOTES";
        SA24HWFBOHAIWAVEDIR.ParameterName = "@SA24HWFBOHAIWAVEDIR";
        SA24HWFBOHAISURGEDIR.ParameterName = "@SA24HWFBOHAISURGEDIR";
        SA24HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA24HWFNORTHOFYSWAVEHEIGHT";
        SA24HWFNORTHOFYSWAVEDIR.ParameterName = "@SA24HWFNORTHOFYSWAVEDIR";
        SA24HWFNORTHOFYSSURGEDIR.ParameterName = "@SA24HWFNORTHOFYSSURGEDIR";
        SA24HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA24HWFMIDDLEOFYSWAVEHEIGHT";
        SA24HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA24HWFMIDDLEOFYSWAVEDIR";
        SA24HWFBOHAIWAVETYPE.ParameterName = "@SA24HWFBOHAIWAVETYPE";
        SA24HWFNORTHOFYSWAVETYPE.ParameterName = "@SA24HWFNORTHOFYSWAVETYPE";
        SA24HWFMIDDLEOFYSWAVETYPE.ParameterName = "@SA24HWFMIDDLEOFYSWAVETYPE";




        PUBLISHDATE.Value = TBLSEAAREA24HWAVEFORECAST.PUBLISHDATE.ToString();
        SA24HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSSURGEDIR;
        SA24HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVEHEIGHT;
        SA24HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVEDIR;
        SA24HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSSURGEDIR;
        SA24HWFQDOFFSHOREWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVEHEIGHT;
        SA24HWFQDOFFSHOREWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVEDIR;
        SA24HWFQDOFFSHORESURGESTATE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHORESURGESTATE;
        SA24HWFQDOFFSHORESURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHORESURGEDIR;
        SA24HWFBOHAIWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVENOTES;
        SA24HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVENOTES;
        SA24HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVEHEIGHT;
        SA24HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVENOTES;
        SA24HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVENOTES;
        SA24HWFQDOFFSHOREWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVENOTES;
        SA24HWFBOHAIWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVEDIR;
        SA24HWFBOHAISURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAISURGEDIR;
        SA24HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVEHEIGHT;
        SA24HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVEDIR;
        SA24HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSSURGEDIR;
        SA24HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVEHEIGHT;
        SA24HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVEDIR;
        SA24HWFBOHAIWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVETYPE;
        SA24HWFNORTHOFYSWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVETYPE;
        SA24HWFMIDDLEOFYSWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVETYPE;


        DbParameter[] parameters = { PUBLISHDATE, SA24HWFMIDDLEOFYSSURGEDIR, SA24HWFSOUTHOFYSWAVEHEIGHT, SA24HWFSOUTHOFYSWAVEDIR,
            SA24HWFSOUTHOFYSSURGEDIR, SA24HWFQDOFFSHOREWAVEHEIGHT, SA24HWFQDOFFSHOREWAVEDIR,
            SA24HWFQDOFFSHORESURGESTATE, SA24HWFQDOFFSHORESURGEDIR, SA24HWFBOHAIWAVENOTES,
            SA24HWFNORTHOFYSWAVENOTES, SA24HWFBOHAIWAVEHEIGHT, SA24HWFMIDDLEOFYSWAVENOTES,
            SA24HWFSOUTHOFYSWAVENOTES, SA24HWFQDOFFSHOREWAVENOTES, SA24HWFBOHAIWAVEDIR,
            SA24HWFBOHAISURGEDIR, SA24HWFNORTHOFYSWAVEHEIGHT, SA24HWFNORTHOFYSWAVEDIR,
            SA24HWFNORTHOFYSSURGEDIR, SA24HWFMIDDLEOFYSWAVEHEIGHT, SA24HWFMIDDLEOFYSWAVEDIR,
            SA24HWFBOHAIWAVETYPE,SA24HWFNORTHOFYSWAVETYPE,SA24HWFMIDDLEOFYSWAVETYPE
        };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改海区24小时海浪预报预报
    /// </summary>
    public int Edit_TBLSEAAREA24HWAVEFORECAST(TBLSEAAREA24HWAVEFORECAST TBLSEAAREA24HWAVEFORECAST)
    {
        string sql = "UPDATE   TBLSEAAREA24HWAVEFORECAST set	SA24HWFMIDDLEOFYSSURGEDIR=@SA24HWFMIDDLEOFYSSURGEDIR,"
            +"SA24HWFSOUTHOFYSWAVEHEIGHT=@SA24HWFSOUTHOFYSWAVEHEIGHT,SA24HWFSOUTHOFYSWAVEDIR=@SA24HWFSOUTHOFYSWAVEDIR,"
            +"SA24HWFSOUTHOFYSSURGEDIR=@SA24HWFSOUTHOFYSSURGEDIR,SA24HWFQDOFFSHOREWAVEHEIGHT=@SA24HWFQDOFFSHOREWAVEHEIGHT,"
            +"SA24HWFQDOFFSHOREWAVEDIR=@SA24HWFQDOFFSHOREWAVEDIR,SA24HWFQDOFFSHORESURGESTATE=@SA24HWFQDOFFSHORESURGESTATE,"
            +"SA24HWFQDOFFSHORESURGEDIR=@SA24HWFQDOFFSHORESURGEDIR,SA24HWFBOHAIWAVENOTES=@SA24HWFBOHAIWAVENOTES,"
            +"SA24HWFNORTHOFYSWAVENOTES=@SA24HWFNORTHOFYSWAVENOTES,SA24HWFBOHAIWAVEHEIGHT=@SA24HWFBOHAIWAVEHEIGHT,"
            +"SA24HWFMIDDLEOFYSWAVENOTES=@SA24HWFMIDDLEOFYSWAVENOTES,SA24HWFSOUTHOFYSWAVENOTES=@SA24HWFSOUTHOFYSWAVENOTES,"
            +"SA24HWFQDOFFSHOREWAVENOTES=@SA24HWFQDOFFSHOREWAVENOTES,SA24HWFBOHAIWAVEDIR=@SA24HWFBOHAIWAVEDIR,"
            +"SA24HWFBOHAISURGEDIR=@SA24HWFBOHAISURGEDIR,SA24HWFNORTHOFYSWAVEHEIGHT=@SA24HWFNORTHOFYSWAVEHEIGHT,"
            +"SA24HWFNORTHOFYSWAVEDIR=@SA24HWFNORTHOFYSWAVEDIR,SA24HWFNORTHOFYSSURGEDIR=@SA24HWFNORTHOFYSSURGEDIR,"
            +"SA24HWFMIDDLEOFYSWAVEHEIGHT=@SA24HWFMIDDLEOFYSWAVEHEIGHT,SA24HWFMIDDLEOFYSWAVEDIR=@SA24HWFMIDDLEOFYSWAVEDIR,"
            + "SA24HWFBOHAIWAVETYPE=@SA24HWFBOHAIWAVETYPE,SA24HWFNORTHOFYSWAVETYPE=@SA24HWFNORTHOFYSWAVETYPE,"
            + "SA24HWFMIDDLEOFYSWAVETYPE=@SA24HWFMIDDLEOFYSWAVETYPE"
            + " where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHORESURGESTATE = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHORESURGEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFQDOFFSHOREWAVENOTES = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA24HWFBOHAIWAVETYPE = DataExe.GetDbParameter();
        var SA24HWFNORTHOFYSWAVETYPE = DataExe.GetDbParameter();
        var SA24HWFMIDDLEOFYSWAVETYPE = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA24HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA24HWFMIDDLEOFYSSURGEDIR";
        SA24HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA24HWFSOUTHOFYSWAVEHEIGHT";
        SA24HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA24HWFSOUTHOFYSWAVEDIR";
        SA24HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA24HWFSOUTHOFYSSURGEDIR";
        SA24HWFQDOFFSHOREWAVEHEIGHT.ParameterName = "@SA24HWFQDOFFSHOREWAVEHEIGHT";
        SA24HWFQDOFFSHOREWAVEDIR.ParameterName = "@SA24HWFQDOFFSHOREWAVEDIR";
        SA24HWFQDOFFSHORESURGESTATE.ParameterName = "@SA24HWFQDOFFSHORESURGESTATE";
        SA24HWFQDOFFSHORESURGEDIR.ParameterName = "@SA24HWFQDOFFSHORESURGEDIR";
        SA24HWFBOHAIWAVENOTES.ParameterName = "@SA24HWFBOHAIWAVENOTES";
        SA24HWFNORTHOFYSWAVENOTES.ParameterName = "@SA24HWFNORTHOFYSWAVENOTES";
        SA24HWFBOHAIWAVEHEIGHT.ParameterName = "@SA24HWFBOHAIWAVEHEIGHT";
        SA24HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA24HWFMIDDLEOFYSWAVENOTES";
        SA24HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA24HWFSOUTHOFYSWAVENOTES";
        SA24HWFQDOFFSHOREWAVENOTES.ParameterName = "@SA24HWFQDOFFSHOREWAVENOTES";
        SA24HWFBOHAIWAVEDIR.ParameterName = "@SA24HWFBOHAIWAVEDIR";
        SA24HWFBOHAISURGEDIR.ParameterName = "@SA24HWFBOHAISURGEDIR";
        SA24HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA24HWFNORTHOFYSWAVEHEIGHT";
        SA24HWFNORTHOFYSWAVEDIR.ParameterName = "@SA24HWFNORTHOFYSWAVEDIR";
        SA24HWFNORTHOFYSSURGEDIR.ParameterName = "@SA24HWFNORTHOFYSSURGEDIR";
        SA24HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA24HWFMIDDLEOFYSWAVEHEIGHT";
        SA24HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA24HWFMIDDLEOFYSWAVEDIR";
        SA24HWFBOHAIWAVETYPE.ParameterName = "@SA24HWFBOHAIWAVETYPE";
        SA24HWFNORTHOFYSWAVETYPE.ParameterName = "@SA24HWFNORTHOFYSWAVETYPE";
        SA24HWFMIDDLEOFYSWAVETYPE.ParameterName = "@SA24HWFMIDDLEOFYSWAVETYPE";


        PUBLISHDATE.Value = TBLSEAAREA24HWAVEFORECAST.PUBLISHDATE.ToString();
        SA24HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSSURGEDIR;
        SA24HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVEHEIGHT;
        SA24HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVEDIR;
        SA24HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSSURGEDIR;
        SA24HWFQDOFFSHOREWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVEHEIGHT;
        SA24HWFQDOFFSHOREWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVEDIR;
        SA24HWFQDOFFSHORESURGESTATE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHORESURGESTATE;
        SA24HWFQDOFFSHORESURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHORESURGEDIR;
        SA24HWFBOHAIWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVENOTES;
        SA24HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVENOTES;
        SA24HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVEHEIGHT;
        SA24HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVENOTES;
        SA24HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFSOUTHOFYSWAVENOTES;
        SA24HWFQDOFFSHOREWAVENOTES.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFQDOFFSHOREWAVENOTES;
        SA24HWFBOHAIWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVEDIR;
        SA24HWFBOHAISURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAISURGEDIR;
        SA24HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVEHEIGHT;
        SA24HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVEDIR;
        SA24HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSSURGEDIR;
        SA24HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVEHEIGHT;
        SA24HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVEDIR;
        SA24HWFBOHAIWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFBOHAIWAVETYPE;
        SA24HWFNORTHOFYSWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFNORTHOFYSWAVETYPE;
        SA24HWFMIDDLEOFYSWAVETYPE.Value = TBLSEAAREA24HWAVEFORECAST.SA24HWFMIDDLEOFYSWAVETYPE;


        DbParameter[] parameters = { PUBLISHDATE, SA24HWFMIDDLEOFYSSURGEDIR, SA24HWFSOUTHOFYSWAVEHEIGHT,
            SA24HWFSOUTHOFYSWAVEDIR, SA24HWFSOUTHOFYSSURGEDIR, SA24HWFQDOFFSHOREWAVEHEIGHT,
            SA24HWFQDOFFSHOREWAVEDIR, SA24HWFQDOFFSHORESURGESTATE, SA24HWFQDOFFSHORESURGEDIR,
            SA24HWFBOHAIWAVENOTES, SA24HWFNORTHOFYSWAVENOTES, SA24HWFBOHAIWAVEHEIGHT,
            SA24HWFMIDDLEOFYSWAVENOTES, SA24HWFSOUTHOFYSWAVENOTES, SA24HWFQDOFFSHOREWAVENOTES,
            SA24HWFBOHAIWAVEDIR, SA24HWFBOHAISURGEDIR, SA24HWFNORTHOFYSWAVEHEIGHT, SA24HWFNORTHOFYSWAVEDIR,
            SA24HWFNORTHOFYSSURGEDIR, SA24HWFMIDDLEOFYSWAVEHEIGHT, SA24HWFMIDDLEOFYSWAVEDIR,
            SA24HWFBOHAIWAVETYPE,SA24HWFNORTHOFYSWAVETYPE,SA24HWFMIDDLEOFYSWAVETYPE};
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改海区24小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

