
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 青岛24小时潮位
/// </summary>
/// <returns></returns>
public class sql_TBLQD24HTIDELEVEL
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLQD24HTIDELEVEL()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有青岛24小时潮位预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLQD24HTIDELEVEL_AllData(TBLQD24HTIDELEVEL TBLQD24HTIDELEVEL)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLQD24HTIDELEVEL where PUBLISHDATE=to_date('" + TBLQD24HTIDELEVEL.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取青岛24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增青岛24小时潮位预报
    /// 1127  贾--------添加quanxian参数，并对quanxian参数进行if判断
    /// </summary>
    /// <returns></returns>
    public int Add_TBLQD24HTIDELEVEL(TBLQD24HTIDELEVEL TBLQD24HTIDELEVEL, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "cx")
        {
            sql = "INSERT INTO  TBLQD24HTIDELEVEL (PUBLISHDATE,QDTLSECONDHIGHWAVEHEIGHT,QDTLSECONDLOWWAVEHOUR,QDTLSECONDLOWWAVEMINUTE,QDTLSECONDLOWWAVEHEIGHT,QDTLFIRSTHIGHWAVEHOUR,"
                +"QDTLFIRSTHIGHWAVEMINUTE,QDTLFIRSTHIGHWAVEHEIGHT,QDTLFIRSTLOWWAVEHOUR,QDTLFIRSTLOWWAVEMINUTE,QDTLFIRSTLOWWAVEHEIGHT,QDTLSECONDHIGHWAVEHOUR,QDTLSECONDHIGHWAVEMINUTE"
                //+",QDTLTOMORROWWAVEHEIGHT,QDTLTOMORROWWAVEDIR"
                + ") VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@QDTLSECONDHIGHWAVEHEIGHT,@QDTLSECONDLOWWAVEHOUR,@QDTLSECONDLOWWAVEMINUTE,"
                +"@QDTLSECONDLOWWAVEHEIGHT,@QDTLFIRSTHIGHWAVEHOUR,@QDTLFIRSTHIGHWAVEMINUTE,@QDTLFIRSTHIGHWAVEHEIGHT,@QDTLFIRSTLOWWAVEHOUR,@QDTLFIRSTLOWWAVEMINUTE,@QDTLFIRSTLOWWAVEHEIGHT,"
                +"@QDTLSECONDHIGHWAVEHOUR,@QDTLSECONDHIGHWAVEMINUTE"
                //+ "  ,@QDTLTOMORROWWAVEHEIGHT,@QDTLTOMORROWWAVEDIR"
                + ")";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEHOUR = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();
            //var QDTLTOMORROWWAVEHEIGHT = DataExe.GetDbParameter();
            //var QDTLTOMORROWWAVEDIR = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEHOUR = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEHOUR = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEHOUR = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEMINUTE = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDTLSECONDHIGHWAVEHEIGHT.ParameterName = "@QDTLSECONDHIGHWAVEHEIGHT";
            QDTLSECONDLOWWAVEHOUR.ParameterName = "@QDTLSECONDLOWWAVEHOUR";
            QDTLSECONDLOWWAVEMINUTE.ParameterName = "@QDTLSECONDLOWWAVEMINUTE";
            QDTLSECONDLOWWAVEHEIGHT.ParameterName = "@QDTLSECONDLOWWAVEHEIGHT";
            //QDTLTOMORROWWAVEHEIGHT.ParameterName = "@QDTLTOMORROWWAVEHEIGHT";
            //QDTLTOMORROWWAVEDIR.ParameterName = "@QDTLTOMORROWWAVEDIR";
            QDTLFIRSTHIGHWAVEHOUR.ParameterName = "@QDTLFIRSTHIGHWAVEHOUR";
            QDTLFIRSTHIGHWAVEMINUTE.ParameterName = "@QDTLFIRSTHIGHWAVEMINUTE";
            QDTLFIRSTHIGHWAVEHEIGHT.ParameterName = "@QDTLFIRSTHIGHWAVEHEIGHT";
            QDTLFIRSTLOWWAVEHOUR.ParameterName = "@QDTLFIRSTLOWWAVEHOUR";
            QDTLFIRSTLOWWAVEMINUTE.ParameterName = "@QDTLFIRSTLOWWAVEMINUTE";
            QDTLFIRSTLOWWAVEHEIGHT.ParameterName = "@QDTLFIRSTLOWWAVEHEIGHT";
            QDTLSECONDHIGHWAVEHOUR.ParameterName = "@QDTLSECONDHIGHWAVEHOUR";
            QDTLSECONDHIGHWAVEMINUTE.ParameterName = "@QDTLSECONDHIGHWAVEMINUTE";

            PUBLISHDATE.Value = TBLQD24HTIDELEVEL.PUBLISHDATE.ToString();
            QDTLSECONDHIGHWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEHEIGHT;
            QDTLSECONDLOWWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEHOUR;
            QDTLSECONDLOWWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEMINUTE;
            QDTLSECONDLOWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEHEIGHT;
            //QDTLTOMORROWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEHEIGHT;
            //QDTLTOMORROWWAVEDIR.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEDIR;
            QDTLFIRSTHIGHWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEHOUR;
            QDTLFIRSTHIGHWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEMINUTE;
            QDTLFIRSTHIGHWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEHEIGHT;
            QDTLFIRSTLOWWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEHOUR;
            QDTLFIRSTLOWWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEMINUTE;
            QDTLFIRSTLOWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEHEIGHT;
            QDTLSECONDHIGHWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEHOUR;
            QDTLSECONDHIGHWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEMINUTE;

            parameters = new DbParameter[] { PUBLISHDATE, QDTLSECONDHIGHWAVEHEIGHT, QDTLSECONDLOWWAVEHOUR, QDTLSECONDLOWWAVEMINUTE, QDTLSECONDLOWWAVEHEIGHT, QDTLFIRSTHIGHWAVEHOUR, QDTLFIRSTHIGHWAVEMINUTE, QDTLFIRSTHIGHWAVEHEIGHT, QDTLFIRSTLOWWAVEHOUR, QDTLFIRSTLOWWAVEMINUTE, QDTLFIRSTLOWWAVEHEIGHT, QDTLSECONDHIGHWAVEHOUR, QDTLSECONDHIGHWAVEMINUTE };

        }
        else if (quanxian.ToLower() == "fl")
        {
            sql = "INSERT INTO  TBLQD24HTIDELEVEL (PUBLISHDATE,QDTLTOMORROWWAVEHEIGHT,QDTLTOMORROWWAVEDIR) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@QDTLTOMORROWWAVEHEIGHT,@QDTLTOMORROWWAVEDIR)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDTLTOMORROWWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLTOMORROWWAVEDIR = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDTLTOMORROWWAVEHEIGHT.ParameterName = "@QDTLTOMORROWWAVEHEIGHT";
            QDTLTOMORROWWAVEDIR.ParameterName = "@QDTLTOMORROWWAVEDIR";

            PUBLISHDATE.Value = TBLQD24HTIDELEVEL.PUBLISHDATE.ToString();
            QDTLTOMORROWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEHEIGHT;
            QDTLTOMORROWWAVEDIR.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEDIR;

            parameters = new DbParameter[] { PUBLISHDATE, QDTLTOMORROWWAVEHEIGHT, QDTLTOMORROWWAVEDIR };


        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增青岛24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改青岛24小时潮位预报
    /// 1127  贾------------添加权限参数并进行判断类型
    /// </summary>
    public int Edit_TBLQD24HTIDELEVEL(TBLQD24HTIDELEVEL TBLQD24HTIDELEVEL, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "cx")
        {
            sql = "UPDATE   TBLQD24HTIDELEVEL set	QDTLSECONDHIGHWAVEHEIGHT=@QDTLSECONDHIGHWAVEHEIGHT,QDTLSECONDLOWWAVEHOUR=@QDTLSECONDLOWWAVEHOUR,QDTLSECONDLOWWAVEMINUTE=@QDTLSECONDLOWWAVEMINUTE,QDTLSECONDLOWWAVEHEIGHT=@QDTLSECONDLOWWAVEHEIGHT,QDTLFIRSTHIGHWAVEHOUR=@QDTLFIRSTHIGHWAVEHOUR,QDTLFIRSTHIGHWAVEMINUTE=@QDTLFIRSTHIGHWAVEMINUTE,QDTLFIRSTHIGHWAVEHEIGHT=@QDTLFIRSTHIGHWAVEHEIGHT,QDTLFIRSTLOWWAVEHOUR=@QDTLFIRSTLOWWAVEHOUR,QDTLFIRSTLOWWAVEMINUTE=@QDTLFIRSTLOWWAVEMINUTE,QDTLFIRSTLOWWAVEHEIGHT=@QDTLFIRSTLOWWAVEHEIGHT,QDTLSECONDHIGHWAVEHOUR=@QDTLSECONDHIGHWAVEHOUR,QDTLSECONDHIGHWAVEMINUTE=@QDTLSECONDHIGHWAVEMINUTE  "

                //+ " ,QDTLTOMORROWWAVEHEIGHT=@QDTLTOMORROWWAVEHEIGHT,QDTLTOMORROWWAVEDIR=@QDTLTOMORROWWAVEDIR "
                +" where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEHOUR = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();
            //var QDTLTOMORROWWAVEHEIGHT = DataExe.GetDbParameter();
            //var QDTLTOMORROWWAVEDIR = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEHOUR = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEHOUR = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEMINUTE = DataExe.GetDbParameter();
            var QDTLFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEHOUR = DataExe.GetDbParameter();
            var QDTLSECONDHIGHWAVEMINUTE = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDTLSECONDHIGHWAVEHEIGHT.ParameterName = "@QDTLSECONDHIGHWAVEHEIGHT";
            QDTLSECONDLOWWAVEHOUR.ParameterName = "@QDTLSECONDLOWWAVEHOUR";
            QDTLSECONDLOWWAVEMINUTE.ParameterName = "@QDTLSECONDLOWWAVEMINUTE";
            QDTLSECONDLOWWAVEHEIGHT.ParameterName = "@QDTLSECONDLOWWAVEHEIGHT";
            //QDTLTOMORROWWAVEHEIGHT.ParameterName = "@QDTLTOMORROWWAVEHEIGHT";
            //QDTLTOMORROWWAVEDIR.ParameterName = "@QDTLTOMORROWWAVEDIR";
            QDTLFIRSTHIGHWAVEHOUR.ParameterName = "@QDTLFIRSTHIGHWAVEHOUR";
            QDTLFIRSTHIGHWAVEMINUTE.ParameterName = "@QDTLFIRSTHIGHWAVEMINUTE";
            QDTLFIRSTHIGHWAVEHEIGHT.ParameterName = "@QDTLFIRSTHIGHWAVEHEIGHT";
            QDTLFIRSTLOWWAVEHOUR.ParameterName = "@QDTLFIRSTLOWWAVEHOUR";
            QDTLFIRSTLOWWAVEMINUTE.ParameterName = "@QDTLFIRSTLOWWAVEMINUTE";
            QDTLFIRSTLOWWAVEHEIGHT.ParameterName = "@QDTLFIRSTLOWWAVEHEIGHT";
            QDTLSECONDHIGHWAVEHOUR.ParameterName = "@QDTLSECONDHIGHWAVEHOUR";
            QDTLSECONDHIGHWAVEMINUTE.ParameterName = "@QDTLSECONDHIGHWAVEMINUTE";

            PUBLISHDATE.Value = TBLQD24HTIDELEVEL.PUBLISHDATE.ToString();
            QDTLSECONDHIGHWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEHEIGHT;
            QDTLSECONDLOWWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEHOUR;
            QDTLSECONDLOWWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEMINUTE;
            QDTLSECONDLOWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLSECONDLOWWAVEHEIGHT;
            //QDTLTOMORROWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEHEIGHT;
            //QDTLTOMORROWWAVEDIR.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEDIR;
            QDTLFIRSTHIGHWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEHOUR;
            QDTLFIRSTHIGHWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEMINUTE;
            QDTLFIRSTHIGHWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLFIRSTHIGHWAVEHEIGHT;
            QDTLFIRSTLOWWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEHOUR;
            QDTLFIRSTLOWWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEMINUTE;
            QDTLFIRSTLOWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLFIRSTLOWWAVEHEIGHT;
            QDTLSECONDHIGHWAVEHOUR.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEHOUR;
            QDTLSECONDHIGHWAVEMINUTE.Value = TBLQD24HTIDELEVEL.QDTLSECONDHIGHWAVEMINUTE;

            parameters = new DbParameter[] { PUBLISHDATE, QDTLSECONDHIGHWAVEHEIGHT, QDTLSECONDLOWWAVEHOUR, QDTLSECONDLOWWAVEMINUTE, QDTLSECONDLOWWAVEHEIGHT, QDTLFIRSTHIGHWAVEHOUR, QDTLFIRSTHIGHWAVEMINUTE, QDTLFIRSTHIGHWAVEHEIGHT, QDTLFIRSTLOWWAVEHOUR, QDTLFIRSTLOWWAVEMINUTE, QDTLFIRSTLOWWAVEHEIGHT, QDTLSECONDHIGHWAVEHOUR, QDTLSECONDHIGHWAVEMINUTE };

        }
        else if (quanxian.ToLower() == "fl")
        {
            sql = "UPDATE   TBLQD24HTIDELEVEL set	QDTLTOMORROWWAVEHEIGHT=@QDTLTOMORROWWAVEHEIGHT,QDTLTOMORROWWAVEDIR=@QDTLTOMORROWWAVEDIR where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";
            
            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDTLTOMORROWWAVEHEIGHT = DataExe.GetDbParameter();
            var QDTLTOMORROWWAVEDIR = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDTLTOMORROWWAVEHEIGHT.ParameterName = "@QDTLTOMORROWWAVEHEIGHT";
            QDTLTOMORROWWAVEDIR.ParameterName = "@QDTLTOMORROWWAVEDIR";

            PUBLISHDATE.Value = TBLQD24HTIDELEVEL.PUBLISHDATE.ToString();
            QDTLTOMORROWWAVEHEIGHT.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEHEIGHT;
            QDTLTOMORROWWAVEDIR.Value = TBLQD24HTIDELEVEL.QDTLTOMORROWWAVEDIR;

            parameters = new DbParameter[] { PUBLISHDATE,  QDTLTOMORROWWAVEHEIGHT, QDTLTOMORROWWAVEDIR };

        }
        
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改青岛24小时潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

