
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 海区48小时海浪预报
/// </summary>
/// <returns></returns>
public class sql_TBLSEAAREA48HWAVEFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLSEAAREA48HWAVEFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有海区48小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLSEAAREA48HWAVEFORECAST_AllData(TBLSEAAREA48HWAVEFORECAST TBLSEAAREA48HWAVEFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLSEAAREA48HWAVEFORECAST where PUBLISHDATE=to_date('" + TBLSEAAREA48HWAVEFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取海区48小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增海区48小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLSEAAREA48HWAVEFORECAST(TBLSEAAREA48HWAVEFORECAST TBLSEAAREA48HWAVEFORECAST)
    {

        string sql = "INSERT INTO  TBLSEAAREA48HWAVEFORECAST (PUBLISHDATE,SA48HWFMIDDLEOFYSWAVEHEIGHT,SA48HWFMIDDLEOFYSWAVEDIR,SA48HWFMIDDLEOFYSSURGEDIR,SA48HWFMIDDLEOFYSWAVENOTES,SA48HWFSOUTHOFYSWAVEHEIGHT,SA48HWFSOUTHOFYSWAVEDIR,SA48HWFSOUTHOFYSSURGEDIR,SA48HWFSOUTHOFYSWAVENOTES,SA48HWFBOHAIWAVEHEIGHT,SA48HWFBOHAIWAVEDIR,SA48HWFBOHAISURGEDIR,SA48HWFBOHAIWAVENOTES,SA48HWFNORTHOFYSWAVEHEIGHT,SA48HWFNORTHOFYSWAVEDIR,SA48HWFNORTHOFYSSURGEDIR,SA48HWFNORTHOFYSWAVENOTES) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@SA48HWFMIDDLEOFYSWAVEHEIGHT,@SA48HWFMIDDLEOFYSWAVEDIR,@SA48HWFMIDDLEOFYSSURGEDIR,@SA48HWFMIDDLEOFYSWAVENOTES,@SA48HWFSOUTHOFYSWAVEHEIGHT,@SA48HWFSOUTHOFYSWAVEDIR,@SA48HWFSOUTHOFYSSURGEDIR,@SA48HWFSOUTHOFYSWAVENOTES,@SA48HWFBOHAIWAVEHEIGHT,@SA48HWFBOHAIWAVEDIR,@SA48HWFBOHAISURGEDIR,@SA48HWFBOHAIWAVENOTES,@SA48HWFNORTHOFYSWAVEHEIGHT,@SA48HWFNORTHOFYSWAVEDIR,@SA48HWFNORTHOFYSSURGEDIR,@SA48HWFNORTHOFYSWAVENOTES)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA48HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA48HWFMIDDLEOFYSWAVEHEIGHT";
        SA48HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA48HWFMIDDLEOFYSWAVEDIR";
        SA48HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA48HWFMIDDLEOFYSSURGEDIR";
        SA48HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA48HWFMIDDLEOFYSWAVENOTES";
        SA48HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA48HWFSOUTHOFYSWAVEHEIGHT";
        SA48HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA48HWFSOUTHOFYSWAVEDIR";
        SA48HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA48HWFSOUTHOFYSSURGEDIR";
        SA48HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA48HWFSOUTHOFYSWAVENOTES";
        SA48HWFBOHAIWAVEHEIGHT.ParameterName = "@SA48HWFBOHAIWAVEHEIGHT";
        SA48HWFBOHAIWAVEDIR.ParameterName = "@SA48HWFBOHAIWAVEDIR";
        SA48HWFBOHAISURGEDIR.ParameterName = "@SA48HWFBOHAISURGEDIR";
        SA48HWFBOHAIWAVENOTES.ParameterName = "@SA48HWFBOHAIWAVENOTES";
        SA48HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA48HWFNORTHOFYSWAVEHEIGHT";
        SA48HWFNORTHOFYSWAVEDIR.ParameterName = "@SA48HWFNORTHOFYSWAVEDIR";
        SA48HWFNORTHOFYSSURGEDIR.ParameterName = "@SA48HWFNORTHOFYSSURGEDIR";
        SA48HWFNORTHOFYSWAVENOTES.ParameterName = "@SA48HWFNORTHOFYSWAVENOTES";




        PUBLISHDATE.Value = TBLSEAAREA48HWAVEFORECAST.PUBLISHDATE.ToString();
        SA48HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVEHEIGHT;
        SA48HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVEDIR;
        SA48HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSSURGEDIR;
        SA48HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVENOTES;
        SA48HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVEHEIGHT;
        SA48HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVEDIR;
        SA48HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSSURGEDIR;
        SA48HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVENOTES;
        SA48HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVEHEIGHT;
        SA48HWFBOHAIWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVEDIR;
        SA48HWFBOHAISURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAISURGEDIR;
        SA48HWFBOHAIWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVENOTES;
        SA48HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVEHEIGHT;
        SA48HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVEDIR;
        SA48HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSSURGEDIR;
        SA48HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVENOTES;


        DbParameter[] parameters = { PUBLISHDATE, SA48HWFMIDDLEOFYSWAVEHEIGHT, SA48HWFMIDDLEOFYSWAVEDIR, SA48HWFMIDDLEOFYSSURGEDIR, SA48HWFMIDDLEOFYSWAVENOTES, SA48HWFSOUTHOFYSWAVEHEIGHT, SA48HWFSOUTHOFYSWAVEDIR, SA48HWFSOUTHOFYSSURGEDIR, SA48HWFSOUTHOFYSWAVENOTES, SA48HWFBOHAIWAVEHEIGHT, SA48HWFBOHAIWAVEDIR, SA48HWFBOHAISURGEDIR, SA48HWFBOHAIWAVENOTES, SA48HWFNORTHOFYSWAVEHEIGHT, SA48HWFNORTHOFYSWAVEDIR, SA48HWFNORTHOFYSSURGEDIR, SA48HWFNORTHOFYSWAVENOTES };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增海区48小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改海区48小时海浪预报预报
    /// </summary>
    public int Edit_TBLSEAAREA48HWAVEFORECAST(TBLSEAAREA48HWAVEFORECAST TBLSEAAREA48HWAVEFORECAST)
    {
        string sql = "UPDATE   TBLSEAAREA48HWAVEFORECAST set	SA48HWFMIDDLEOFYSWAVEHEIGHT=@SA48HWFMIDDLEOFYSWAVEHEIGHT,SA48HWFMIDDLEOFYSWAVEDIR=@SA48HWFMIDDLEOFYSWAVEDIR,SA48HWFMIDDLEOFYSSURGEDIR=@SA48HWFMIDDLEOFYSSURGEDIR,SA48HWFMIDDLEOFYSWAVENOTES=@SA48HWFMIDDLEOFYSWAVENOTES,SA48HWFSOUTHOFYSWAVEHEIGHT=@SA48HWFSOUTHOFYSWAVEHEIGHT,SA48HWFSOUTHOFYSWAVEDIR=@SA48HWFSOUTHOFYSWAVEDIR,SA48HWFSOUTHOFYSSURGEDIR=@SA48HWFSOUTHOFYSSURGEDIR,SA48HWFSOUTHOFYSWAVENOTES=@SA48HWFSOUTHOFYSWAVENOTES,SA48HWFBOHAIWAVEHEIGHT=@SA48HWFBOHAIWAVEHEIGHT,SA48HWFBOHAIWAVEDIR=@SA48HWFBOHAIWAVEDIR,SA48HWFBOHAISURGEDIR=@SA48HWFBOHAISURGEDIR,SA48HWFBOHAIWAVENOTES=@SA48HWFBOHAIWAVENOTES,SA48HWFNORTHOFYSWAVEHEIGHT=@SA48HWFNORTHOFYSWAVEHEIGHT,SA48HWFNORTHOFYSWAVEDIR=@SA48HWFNORTHOFYSWAVEDIR,SA48HWFNORTHOFYSSURGEDIR=@SA48HWFNORTHOFYSSURGEDIR,SA48HWFNORTHOFYSWAVENOTES=@SA48HWFNORTHOFYSWAVENOTES where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA48HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA48HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA48HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA48HWFMIDDLEOFYSWAVEHEIGHT";
        SA48HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA48HWFMIDDLEOFYSWAVEDIR";
        SA48HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA48HWFMIDDLEOFYSSURGEDIR";
        SA48HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA48HWFMIDDLEOFYSWAVENOTES";
        SA48HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA48HWFSOUTHOFYSWAVEHEIGHT";
        SA48HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA48HWFSOUTHOFYSWAVEDIR";
        SA48HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA48HWFSOUTHOFYSSURGEDIR";
        SA48HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA48HWFSOUTHOFYSWAVENOTES";
        SA48HWFBOHAIWAVEHEIGHT.ParameterName = "@SA48HWFBOHAIWAVEHEIGHT";
        SA48HWFBOHAIWAVEDIR.ParameterName = "@SA48HWFBOHAIWAVEDIR";
        SA48HWFBOHAISURGEDIR.ParameterName = "@SA48HWFBOHAISURGEDIR";
        SA48HWFBOHAIWAVENOTES.ParameterName = "@SA48HWFBOHAIWAVENOTES";
        SA48HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA48HWFNORTHOFYSWAVEHEIGHT";
        SA48HWFNORTHOFYSWAVEDIR.ParameterName = "@SA48HWFNORTHOFYSWAVEDIR";
        SA48HWFNORTHOFYSSURGEDIR.ParameterName = "@SA48HWFNORTHOFYSSURGEDIR";
        SA48HWFNORTHOFYSWAVENOTES.ParameterName = "@SA48HWFNORTHOFYSWAVENOTES";




        PUBLISHDATE.Value = TBLSEAAREA48HWAVEFORECAST.PUBLISHDATE.ToString();
        SA48HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVEHEIGHT;
        SA48HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVEDIR;
        SA48HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSSURGEDIR;
        SA48HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFMIDDLEOFYSWAVENOTES;
        SA48HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVEHEIGHT;
        SA48HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVEDIR;
        SA48HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSSURGEDIR;
        SA48HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFSOUTHOFYSWAVENOTES;
        SA48HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVEHEIGHT;
        SA48HWFBOHAIWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVEDIR;
        SA48HWFBOHAISURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAISURGEDIR;
        SA48HWFBOHAIWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFBOHAIWAVENOTES;
        SA48HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVEHEIGHT;
        SA48HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVEDIR;
        SA48HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSSURGEDIR;
        SA48HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA48HWAVEFORECAST.SA48HWFNORTHOFYSWAVENOTES;


        DbParameter[] parameters = { PUBLISHDATE, SA48HWFMIDDLEOFYSWAVEHEIGHT, SA48HWFMIDDLEOFYSWAVEDIR, SA48HWFMIDDLEOFYSSURGEDIR, SA48HWFMIDDLEOFYSWAVENOTES, SA48HWFSOUTHOFYSWAVEHEIGHT, SA48HWFSOUTHOFYSWAVEDIR, SA48HWFSOUTHOFYSSURGEDIR, SA48HWFSOUTHOFYSWAVENOTES, SA48HWFBOHAIWAVEHEIGHT, SA48HWFBOHAIWAVEDIR, SA48HWFBOHAISURGEDIR, SA48HWFBOHAIWAVENOTES, SA48HWFNORTHOFYSWAVEHEIGHT, SA48HWFNORTHOFYSWAVEDIR, SA48HWFNORTHOFYSSURGEDIR, SA48HWFNORTHOFYSWAVENOTES };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改海区48小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

