
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 青岛周边海域24小时预报
/// </summary>
/// <returns></returns>
public class sql_TBLQDCIRCUM24HWATERFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLQDCIRCUM24HWATERFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有青岛周边海域24小时预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLQDCIRCUM24HWATERFORECAST_AllData(TBLQDCIRCUM24HWATERFORECAST TBLQDCIRCUM24HWATERFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLQDCIRCUM24HWATERFORECAST where PUBLISHDATE=to_date('" + TBLQDCIRCUM24HWATERFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取青岛周边海域24小时预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增青岛周边海域24小时预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    /// <returns></returns>
    public int Add_TBLQDCIRCUM24HWATERFORECAST(TBLQDCIRCUM24HWATERFORECAST TBLQDCIRCUM24HWATERFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "INSERT INTO  TBLQDCIRCUM24HWATERFORECAST (PUBLISHDATE,QDC24HWFQDOFFSHOREWAVEHEIGHT,QDC24HWFJMOFFSHOREWAVEHEIGHT,QDC24HWFJZWOFFSHOREWAVEHEIGHT,QDC24HWFJNOFFSHOREWAVEHEIGHT) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@QDC24HWFQDOFFSHOREWAVEHEIGHT,@QDC24HWFJMOFFSHOREWAVEHEIGHT,@QDC24HWFJZWOFFSHOREWAVEHEIGHT,@QDC24HWFJNOFFSHOREWAVEHEIGHT)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDC24HWFQDOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJMOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJZWOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJNOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDC24HWFQDOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFQDOFFSHOREWAVEHEIGHT";
            QDC24HWFJMOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJMOFFSHOREWAVEHEIGHT";
            QDC24HWFJZWOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJZWOFFSHOREWAVEHEIGHT";
            QDC24HWFJNOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJNOFFSHOREWAVEHEIGHT";

            PUBLISHDATE.Value = TBLQDCIRCUM24HWATERFORECAST.PUBLISHDATE.ToString();
            QDC24HWFQDOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFQDOFFSHOREWAVEHEIGHT;
            QDC24HWFJMOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJMOFFSHOREWAVEHEIGHT;
            QDC24HWFJZWOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJZWOFFSHOREWAVEHEIGHT;
            QDC24HWFJNOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJNOFFSHOREWAVEHEIGHT;

            parameters = new DbParameter[] { PUBLISHDATE, QDC24HWFQDOFFSHOREWAVEHEIGHT, QDC24HWFJMOFFSHOREWAVEHEIGHT, QDC24HWFJZWOFFSHOREWAVEHEIGHT, QDC24HWFJNOFFSHOREWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {
            sql = "INSERT INTO  TBLQDCIRCUM24HWATERFORECAST (PUBLISHDATE,QDC24HWFQDOFFSHOREWATERTEMP,QDC24HWFJMOFFSHOREWATERTEMP,QDC24HWFJZWOFFSHOREWATERTEMP,QDC24HWFJNOFFSHOREWATERTEMP) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@QDC24HWFQDOFFSHOREWATERTEMP,@QDC24HWFJMOFFSHOREWATERTEMP,@QDC24HWFJZWOFFSHOREWATERTEMP,@QDC24HWFJNOFFSHOREWATERTEMP)";



            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDC24HWFQDOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJMOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJZWOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJNOFFSHOREWATERTEMP = DataExe.GetDbParameter();




            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDC24HWFQDOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFQDOFFSHOREWATERTEMP";
            QDC24HWFJMOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJMOFFSHOREWATERTEMP";
            QDC24HWFJZWOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJZWOFFSHOREWATERTEMP";
            QDC24HWFJNOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJNOFFSHOREWATERTEMP";




            PUBLISHDATE.Value = TBLQDCIRCUM24HWATERFORECAST.PUBLISHDATE.ToString();
            QDC24HWFQDOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFQDOFFSHOREWATERTEMP;
            QDC24HWFJMOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJMOFFSHOREWATERTEMP;
            QDC24HWFJZWOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJZWOFFSHOREWATERTEMP;
            QDC24HWFJNOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJNOFFSHOREWATERTEMP;


            parameters = new DbParameter[] { PUBLISHDATE, QDC24HWFQDOFFSHOREWATERTEMP, QDC24HWFJMOFFSHOREWATERTEMP, QDC24HWFJZWOFFSHOREWATERTEMP, QDC24HWFJNOFFSHOREWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增青岛周边海域24小时预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改青岛周边海域24小时预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    public int Edit_TBLQDCIRCUM24HWATERFORECAST(TBLQDCIRCUM24HWATERFORECAST TBLQDCIRCUM24HWATERFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "UPDATE   TBLQDCIRCUM24HWATERFORECAST set	QDC24HWFQDOFFSHOREWAVEHEIGHT=@QDC24HWFQDOFFSHOREWAVEHEIGHT,QDC24HWFJMOFFSHOREWAVEHEIGHT=@QDC24HWFJMOFFSHOREWAVEHEIGHT,QDC24HWFJZWOFFSHOREWAVEHEIGHT=@QDC24HWFJZWOFFSHOREWAVEHEIGHT,QDC24HWFJNOFFSHOREWAVEHEIGHT=@QDC24HWFJNOFFSHOREWAVEHEIGHT where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDC24HWFQDOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJMOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJZWOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();
            var QDC24HWFJNOFFSHOREWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDC24HWFQDOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFQDOFFSHOREWAVEHEIGHT";
            QDC24HWFJMOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJMOFFSHOREWAVEHEIGHT";
            QDC24HWFJZWOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJZWOFFSHOREWAVEHEIGHT";
            QDC24HWFJNOFFSHOREWAVEHEIGHT.ParameterName = "@QDC24HWFJNOFFSHOREWAVEHEIGHT";

            PUBLISHDATE.Value = TBLQDCIRCUM24HWATERFORECAST.PUBLISHDATE.ToString();
            QDC24HWFQDOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFQDOFFSHOREWAVEHEIGHT;
            QDC24HWFJMOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJMOFFSHOREWAVEHEIGHT;
            QDC24HWFJZWOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJZWOFFSHOREWAVEHEIGHT;
            QDC24HWFJNOFFSHOREWAVEHEIGHT.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJNOFFSHOREWAVEHEIGHT;


            parameters = new DbParameter[] { PUBLISHDATE, QDC24HWFQDOFFSHOREWAVEHEIGHT, QDC24HWFJMOFFSHOREWAVEHEIGHT, QDC24HWFJZWOFFSHOREWAVEHEIGHT, QDC24HWFJNOFFSHOREWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {
            sql = "UPDATE   TBLQDCIRCUM24HWATERFORECAST set	QDC24HWFQDOFFSHOREWATERTEMP=@QDC24HWFQDOFFSHOREWATERTEMP,QDC24HWFJMOFFSHOREWATERTEMP=@QDC24HWFJMOFFSHOREWATERTEMP,QDC24HWFJZWOFFSHOREWATERTEMP=@QDC24HWFJZWOFFSHOREWATERTEMP,QDC24HWFJNOFFSHOREWATERTEMP=@QDC24HWFJNOFFSHOREWATERTEMP where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var QDC24HWFQDOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJMOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJZWOFFSHOREWATERTEMP = DataExe.GetDbParameter();
            var QDC24HWFJNOFFSHOREWATERTEMP = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            QDC24HWFQDOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFQDOFFSHOREWATERTEMP";
            QDC24HWFJMOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJMOFFSHOREWATERTEMP";
            QDC24HWFJZWOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJZWOFFSHOREWATERTEMP";
            QDC24HWFJNOFFSHOREWATERTEMP.ParameterName = "@QDC24HWFJNOFFSHOREWATERTEMP";

            PUBLISHDATE.Value = TBLQDCIRCUM24HWATERFORECAST.PUBLISHDATE.ToString();
            QDC24HWFQDOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFQDOFFSHOREWATERTEMP;
            QDC24HWFJMOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJMOFFSHOREWATERTEMP;
            QDC24HWFJZWOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJZWOFFSHOREWATERTEMP;
            QDC24HWFJNOFFSHOREWATERTEMP.Value = TBLQDCIRCUM24HWATERFORECAST.QDC24HWFJNOFFSHOREWATERTEMP;


            parameters = new DbParameter[] { PUBLISHDATE, QDC24HWFQDOFFSHOREWATERTEMP, QDC24HWFJMOFFSHOREWATERTEMP, QDC24HWFJZWOFFSHOREWATERTEMP, QDC24HWFJNOFFSHOREWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改青岛周边海域24小时预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

