
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 威海电视台未来24h预报
/// </summary>
/// <returns></returns>
public class sql_TBLWEIHAITV24HFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLWEIHAITV24HFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有威海电视台未来24h预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLWEIHAITV24HFORECAST_AllData(TBLWEIHAITV24HFORECAST TBLWEIHAITV24HFORECAST, string searchType = "p")
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLWEIHAITV24HFORECAST where PUBLISHDATE=to_date('" + TBLWEIHAITV24HFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取威海电视台未来24h预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增威海电视台未来24h预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    /// <returns></returns>
    public int Add_TBLWEIHAITV24HFORECAST(TBLWEIHAITV24HFORECAST TBLWEIHAITV24HFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "INSERT INTO  TBLWEIHAITV24HFORECAST (PUBLISHDATE,WTV24HCST24HFWAVEHEIGHT,WTV24HRS24HFWAVEHEIGHT,WTV24HWD48HFWAVEHEIGHT,WTV24HCST48HFWAVEHEIGHT,WTV24HRS48HFWAVEHEIGHT,WTV24HSD24HFWAVEHEIGHT,WTV24HWH48HFWAVEHEIGHT,WTV24HSD48HFWAVEHEIGHT,WTV24HWD24HFWAVEHEIGHT) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@WTV24HCST24HFWAVEHEIGHT,@WTV24HRS24HFWAVEHEIGHT,@WTV24HWD48HFWAVEHEIGHT,@WTV24HCST48HFWAVEHEIGHT,@WTV24HRS48HFWAVEHEIGHT,@WTV24HSD24HFWAVEHEIGHT,@WTV24HWH48HFWAVEHEIGHT,@WTV24HSD48HFWAVEHEIGHT,@WTV24HWD24HFWAVEHEIGHT)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var WTV24HCST24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HRS24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWD48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HCST48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HRS48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HSD24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWH48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HSD48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWD24HFWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            WTV24HCST24HFWAVEHEIGHT.ParameterName = "@WTV24HCST24HFWAVEHEIGHT";
            WTV24HRS24HFWAVEHEIGHT.ParameterName = "@WTV24HRS24HFWAVEHEIGHT";
            WTV24HWD48HFWAVEHEIGHT.ParameterName = "@WTV24HWD48HFWAVEHEIGHT";
            WTV24HCST48HFWAVEHEIGHT.ParameterName = "@WTV24HCST48HFWAVEHEIGHT";
            WTV24HRS48HFWAVEHEIGHT.ParameterName = "@WTV24HRS48HFWAVEHEIGHT";
            WTV24HSD24HFWAVEHEIGHT.ParameterName = "@WTV24HSD24HFWAVEHEIGHT";
            WTV24HWH48HFWAVEHEIGHT.ParameterName = "@WTV24HWH48HFWAVEHEIGHT";
            WTV24HSD48HFWAVEHEIGHT.ParameterName = "@WTV24HSD48HFWAVEHEIGHT";
            WTV24HWD24HFWAVEHEIGHT.ParameterName = "@WTV24HWD24HFWAVEHEIGHT";

            PUBLISHDATE.Value = TBLWEIHAITV24HFORECAST.PUBLISHDATE.ToString();
            WTV24HCST24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HCST24HFWAVEHEIGHT;
            WTV24HRS24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HRS24HFWAVEHEIGHT;
            WTV24HWD48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWD48HFWAVEHEIGHT;
            WTV24HCST48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HCST48HFWAVEHEIGHT;
            WTV24HRS48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HRS48HFWAVEHEIGHT;
            WTV24HSD24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HSD24HFWAVEHEIGHT;
            WTV24HWH48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWH48HFWAVEHEIGHT;
            WTV24HSD48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HSD48HFWAVEHEIGHT;
            WTV24HWD24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWD24HFWAVEHEIGHT;

            parameters = new DbParameter[] { PUBLISHDATE, WTV24HCST24HFWAVEHEIGHT, WTV24HRS24HFWAVEHEIGHT, WTV24HWD48HFWAVEHEIGHT, WTV24HCST48HFWAVEHEIGHT, WTV24HRS48HFWAVEHEIGHT, WTV24HSD24HFWAVEHEIGHT, WTV24HWH48HFWAVEHEIGHT, WTV24HSD48HFWAVEHEIGHT, WTV24HWD24HFWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {

            sql = "INSERT INTO  TBLWEIHAITV24HFORECAST (PUBLISHDATE,WTV24HCST24HFWATERTEMP,WTV24HRS24HFWATERTEMP,WTV24HWD48HFWATERTEMP,WTV24HCST48HFWATERTEMP,WTV24HRS48HFWATERTEMP,WTV24HSD24HFWATERTEMP,WTV24HWH48HFWATERTEMP,WTV24HSD48HFWATERTEMP,WTV24HWD24HFWATERTEMP) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@WTV24HCST24HFWATERTEMP,@WTV24HRS24HFWATERTEMP,@WTV24HWD48HFWATERTEMP,@WTV24HCST48HFWATERTEMP,@WTV24HRS48HFWATERTEMP,@WTV24HSD24HFWATERTEMP,@WTV24HWH48HFWATERTEMP,@WTV24HSD48HFWATERTEMP,@WTV24HWD24HFWATERTEMP)";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var WTV24HCST24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HRS24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWD48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HCST48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HRS48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HSD24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWH48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HSD48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWD24HFWATERTEMP = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            WTV24HCST24HFWATERTEMP.ParameterName = "@WTV24HCST24HFWATERTEMP";
            WTV24HRS24HFWATERTEMP.ParameterName = "@WTV24HRS24HFWATERTEMP";
            WTV24HWD48HFWATERTEMP.ParameterName = "@WTV24HWD48HFWATERTEMP";
            WTV24HCST48HFWATERTEMP.ParameterName = "@WTV24HCST48HFWATERTEMP";
            WTV24HRS48HFWATERTEMP.ParameterName = "@WTV24HRS48HFWATERTEMP";
            WTV24HSD24HFWATERTEMP.ParameterName = "@WTV24HSD24HFWATERTEMP";
            WTV24HWH48HFWATERTEMP.ParameterName = "@WTV24HWH48HFWATERTEMP";
            WTV24HSD48HFWATERTEMP.ParameterName = "@WTV24HSD48HFWATERTEMP";
            WTV24HWD24HFWATERTEMP.ParameterName = "@WTV24HWD24HFWATERTEMP";

            PUBLISHDATE.Value = TBLWEIHAITV24HFORECAST.PUBLISHDATE.ToString();
            WTV24HCST24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HCST24HFWATERTEMP;
            WTV24HRS24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HRS24HFWATERTEMP;
            WTV24HWD48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWD48HFWATERTEMP;
            WTV24HCST48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HCST48HFWATERTEMP;
            WTV24HRS48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HRS48HFWATERTEMP;
            WTV24HSD24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HSD24HFWATERTEMP;
            WTV24HWH48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWH48HFWATERTEMP;
            WTV24HSD48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HSD48HFWATERTEMP;
            WTV24HWD24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWD24HFWATERTEMP;

            parameters = new DbParameter[] { PUBLISHDATE, WTV24HCST24HFWATERTEMP, WTV24HRS24HFWATERTEMP, WTV24HWD48HFWATERTEMP, WTV24HCST48HFWATERTEMP, WTV24HRS48HFWATERTEMP, WTV24HSD24HFWATERTEMP, WTV24HWH48HFWATERTEMP, WTV24HSD48HFWATERTEMP, WTV24HWD24HFWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增威海电视台未来24h预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改威海电视台未来24h预报预报
    /// 1127  贾 ------ 添加quanxian参数
    /// </summary>
    public int Edit_TBLWEIHAITV24HFORECAST(TBLWEIHAITV24HFORECAST TBLWEIHAITV24HFORECAST, string quanxian)
    {
        string sql = null;
        DbParameter[] parameters = null;
        if (quanxian.ToLower() == "fl")
        {
            sql = "UPDATE   TBLWEIHAITV24HFORECAST set	WTV24HCST24HFWAVEHEIGHT=@WTV24HCST24HFWAVEHEIGHT,WTV24HRS24HFWAVEHEIGHT=@WTV24HRS24HFWAVEHEIGHT,WTV24HWD48HFWAVEHEIGHT=@WTV24HWD48HFWAVEHEIGHT,WTV24HCST48HFWAVEHEIGHT=@WTV24HCST48HFWAVEHEIGHT,WTV24HRS48HFWAVEHEIGHT=@WTV24HRS48HFWAVEHEIGHT,WTV24HSD24HFWAVEHEIGHT=@WTV24HSD24HFWAVEHEIGHT,WTV24HWH48HFWAVEHEIGHT=@WTV24HWH48HFWAVEHEIGHT,WTV24HSD48HFWAVEHEIGHT=@WTV24HSD48HFWAVEHEIGHT,WTV24HWD24HFWAVEHEIGHT=@WTV24HWD24HFWAVEHEIGHT where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var WTV24HCST24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HRS24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWD48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HCST48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HRS48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HSD24HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWH48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HSD48HFWAVEHEIGHT = DataExe.GetDbParameter();
            var WTV24HWD24HFWAVEHEIGHT = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            WTV24HCST24HFWAVEHEIGHT.ParameterName = "@WTV24HCST24HFWAVEHEIGHT";
            WTV24HRS24HFWAVEHEIGHT.ParameterName = "@WTV24HRS24HFWAVEHEIGHT";
            WTV24HWD48HFWAVEHEIGHT.ParameterName = "@WTV24HWD48HFWAVEHEIGHT";
            WTV24HCST48HFWAVEHEIGHT.ParameterName = "@WTV24HCST48HFWAVEHEIGHT";
            WTV24HRS48HFWAVEHEIGHT.ParameterName = "@WTV24HRS48HFWAVEHEIGHT";
            WTV24HSD24HFWAVEHEIGHT.ParameterName = "@WTV24HSD24HFWAVEHEIGHT";
            WTV24HWH48HFWAVEHEIGHT.ParameterName = "@WTV24HWH48HFWAVEHEIGHT";
            WTV24HSD48HFWAVEHEIGHT.ParameterName = "@WTV24HSD48HFWAVEHEIGHT";
            WTV24HWD24HFWAVEHEIGHT.ParameterName = "@WTV24HWD24HFWAVEHEIGHT";

            PUBLISHDATE.Value = TBLWEIHAITV24HFORECAST.PUBLISHDATE.ToString();
            WTV24HCST24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HCST24HFWAVEHEIGHT;
            WTV24HRS24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HRS24HFWAVEHEIGHT;
            WTV24HWD48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWD48HFWAVEHEIGHT;
            WTV24HCST48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HCST48HFWAVEHEIGHT;
            WTV24HRS48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HRS48HFWAVEHEIGHT;
            WTV24HSD24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HSD24HFWAVEHEIGHT;
            WTV24HWH48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWH48HFWAVEHEIGHT;
            WTV24HSD48HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HSD48HFWAVEHEIGHT;
            WTV24HWD24HFWAVEHEIGHT.Value = TBLWEIHAITV24HFORECAST.WTV24HWD24HFWAVEHEIGHT;

            parameters = new DbParameter[] { PUBLISHDATE, WTV24HCST24HFWAVEHEIGHT, WTV24HRS24HFWAVEHEIGHT, WTV24HWD48HFWAVEHEIGHT, WTV24HCST48HFWAVEHEIGHT, WTV24HRS48HFWAVEHEIGHT, WTV24HSD24HFWAVEHEIGHT, WTV24HWH48HFWAVEHEIGHT, WTV24HSD48HFWAVEHEIGHT, WTV24HWD24HFWAVEHEIGHT };
        }
        else if (quanxian.ToLower() == "sw")
        {
            sql = "UPDATE   TBLWEIHAITV24HFORECAST set	WTV24HCST24HFWATERTEMP=@WTV24HCST24HFWATERTEMP,WTV24HRS24HFWATERTEMP=@WTV24HRS24HFWATERTEMP,WTV24HWD48HFWATERTEMP=@WTV24HWD48HFWATERTEMP,WTV24HCST48HFWATERTEMP=@WTV24HCST48HFWATERTEMP,WTV24HRS48HFWATERTEMP=@WTV24HRS48HFWATERTEMP,WTV24HSD24HFWATERTEMP=@WTV24HSD24HFWATERTEMP,WTV24HWH48HFWATERTEMP=@WTV24HWH48HFWATERTEMP,WTV24HSD48HFWATERTEMP=@WTV24HSD48HFWATERTEMP,WTV24HWD24HFWATERTEMP=@WTV24HWD24HFWATERTEMP where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";

            var PUBLISHDATE = DataExe.GetDbParameter();
            var WTV24HCST24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HRS24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWD48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HCST48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HRS48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HSD24HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWH48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HSD48HFWATERTEMP = DataExe.GetDbParameter();
            var WTV24HWD24HFWATERTEMP = DataExe.GetDbParameter();

            PUBLISHDATE.ParameterName = "@PUBLISHDATE";
            WTV24HCST24HFWATERTEMP.ParameterName = "@WTV24HCST24HFWATERTEMP";
            WTV24HRS24HFWATERTEMP.ParameterName = "@WTV24HRS24HFWATERTEMP";
            WTV24HWD48HFWATERTEMP.ParameterName = "@WTV24HWD48HFWATERTEMP";
            WTV24HCST48HFWATERTEMP.ParameterName = "@WTV24HCST48HFWATERTEMP";
            WTV24HRS48HFWATERTEMP.ParameterName = "@WTV24HRS48HFWATERTEMP";
            WTV24HSD24HFWATERTEMP.ParameterName = "@WTV24HSD24HFWATERTEMP";
            WTV24HWH48HFWATERTEMP.ParameterName = "@WTV24HWH48HFWATERTEMP";
            WTV24HSD48HFWATERTEMP.ParameterName = "@WTV24HSD48HFWATERTEMP";
            WTV24HWD24HFWATERTEMP.ParameterName = "@WTV24HWD24HFWATERTEMP";

            PUBLISHDATE.Value = TBLWEIHAITV24HFORECAST.PUBLISHDATE.ToString();
            WTV24HCST24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HCST24HFWATERTEMP;
            WTV24HRS24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HRS24HFWATERTEMP;
            WTV24HWD48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWD48HFWATERTEMP;
            WTV24HCST48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HCST48HFWATERTEMP;
            WTV24HRS48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HRS48HFWATERTEMP;
            WTV24HSD24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HSD24HFWATERTEMP;
            WTV24HWH48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWH48HFWATERTEMP;
            WTV24HSD48HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HSD48HFWATERTEMP;
            WTV24HWD24HFWATERTEMP.Value = TBLWEIHAITV24HFORECAST.WTV24HWD24HFWATERTEMP;

            parameters = new DbParameter[] { PUBLISHDATE, WTV24HCST24HFWATERTEMP, WTV24HRS24HFWATERTEMP, WTV24HWD48HFWATERTEMP, WTV24HCST48HFWATERTEMP, WTV24HRS48HFWATERTEMP, WTV24HSD24HFWATERTEMP, WTV24HWH48HFWATERTEMP, WTV24HSD48HFWATERTEMP, WTV24HWD24HFWATERTEMP };
        }

        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改威海电视台未来24h预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

