
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 海区72小时海浪预报
/// </summary>
/// <returns></returns>
public class sql_TBLSEAAREA72HWAVEFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLSEAAREA72HWAVEFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有海区72小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLSEAAREA72HWAVEFORECAST_AllData(TBLSEAAREA72HWAVEFORECAST TBLSEAAREA72HWAVEFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLSEAAREA72HWAVEFORECAST where PUBLISHDATE=to_date('" + TBLSEAAREA72HWAVEFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");
           
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取海区72小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增海区72小时海浪预报预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLSEAAREA72HWAVEFORECAST(TBLSEAAREA72HWAVEFORECAST TBLSEAAREA72HWAVEFORECAST)
    {

        string sql = "INSERT INTO  TBLSEAAREA72HWAVEFORECAST (PUBLISHDATE,SA72HWFMIDDLEOFYSWAVEHEIGHT,SA72HWFMIDDLEOFYSWAVEDIR,SA72HWFMIDDLEOFYSSURGEDIR,SA72HWFMIDDLEOFYSWAVENOTES,SA72HWFSOUTHOFYSWAVEHEIGHT,SA72HWFSOUTHOFYSWAVEDIR,SA72HWFSOUTHOFYSSURGEDIR,SA72HWFSOUTHOFYSWAVENOTES,SA72HWFBOHAIWAVEHEIGHT,SA72HWFBOHAIWAVEDIR,SA72HWFBOHAISURGEDIR,SA72HWFBOHAIWAVENOTES,SA72HWFNORTHOFYSWAVEHEIGHT,SA72HWFNORTHOFYSWAVEDIR,SA72HWFNORTHOFYSSURGEDIR,SA72HWFNORTHOFYSWAVENOTES) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@SA72HWFMIDDLEOFYSWAVEHEIGHT,@SA72HWFMIDDLEOFYSWAVEDIR,@SA72HWFMIDDLEOFYSSURGEDIR,@SA72HWFMIDDLEOFYSWAVENOTES,@SA72HWFSOUTHOFYSWAVEHEIGHT,@SA72HWFSOUTHOFYSWAVEDIR,@SA72HWFSOUTHOFYSSURGEDIR,@SA72HWFSOUTHOFYSWAVENOTES,@SA72HWFBOHAIWAVEHEIGHT,@SA72HWFBOHAIWAVEDIR,@SA72HWFBOHAISURGEDIR,@SA72HWFBOHAIWAVENOTES,@SA72HWFNORTHOFYSWAVEHEIGHT,@SA72HWFNORTHOFYSWAVEDIR,@SA72HWFNORTHOFYSSURGEDIR,@SA72HWFNORTHOFYSWAVENOTES)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA72HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA72HWFMIDDLEOFYSWAVEHEIGHT";
        SA72HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA72HWFMIDDLEOFYSWAVEDIR";
        SA72HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA72HWFMIDDLEOFYSSURGEDIR";
        SA72HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA72HWFMIDDLEOFYSWAVENOTES";
        SA72HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA72HWFSOUTHOFYSWAVEHEIGHT";
        SA72HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA72HWFSOUTHOFYSWAVEDIR";
        SA72HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA72HWFSOUTHOFYSSURGEDIR";
        SA72HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA72HWFSOUTHOFYSWAVENOTES";
        SA72HWFBOHAIWAVEHEIGHT.ParameterName = "@SA72HWFBOHAIWAVEHEIGHT";
        SA72HWFBOHAIWAVEDIR.ParameterName = "@SA72HWFBOHAIWAVEDIR";
        SA72HWFBOHAISURGEDIR.ParameterName = "@SA72HWFBOHAISURGEDIR";
        SA72HWFBOHAIWAVENOTES.ParameterName = "@SA72HWFBOHAIWAVENOTES";
        SA72HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA72HWFNORTHOFYSWAVEHEIGHT";
        SA72HWFNORTHOFYSWAVEDIR.ParameterName = "@SA72HWFNORTHOFYSWAVEDIR";
        SA72HWFNORTHOFYSSURGEDIR.ParameterName = "@SA72HWFNORTHOFYSSURGEDIR";
        SA72HWFNORTHOFYSWAVENOTES.ParameterName = "@SA72HWFNORTHOFYSWAVENOTES";




        PUBLISHDATE.Value = TBLSEAAREA72HWAVEFORECAST.PUBLISHDATE.ToString();
        SA72HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVEHEIGHT;
        SA72HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVEDIR;
        SA72HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSSURGEDIR;
        SA72HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVENOTES;
        SA72HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVEHEIGHT;
        SA72HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVEDIR;
        SA72HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSSURGEDIR;
        SA72HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVENOTES;
        SA72HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVEHEIGHT;
        SA72HWFBOHAIWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVEDIR;
        SA72HWFBOHAISURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAISURGEDIR;
        SA72HWFBOHAIWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVENOTES;
        SA72HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVEHEIGHT;
        SA72HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVEDIR;
        SA72HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSSURGEDIR;
        SA72HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVENOTES;


        DbParameter[] parameters = { PUBLISHDATE, SA72HWFMIDDLEOFYSWAVEHEIGHT, SA72HWFMIDDLEOFYSWAVEDIR, SA72HWFMIDDLEOFYSSURGEDIR, SA72HWFMIDDLEOFYSWAVENOTES, SA72HWFSOUTHOFYSWAVEHEIGHT, SA72HWFSOUTHOFYSWAVEDIR, SA72HWFSOUTHOFYSSURGEDIR, SA72HWFSOUTHOFYSWAVENOTES, SA72HWFBOHAIWAVEHEIGHT, SA72HWFBOHAIWAVEDIR, SA72HWFBOHAISURGEDIR, SA72HWFBOHAIWAVENOTES, SA72HWFNORTHOFYSWAVEHEIGHT, SA72HWFNORTHOFYSWAVEDIR, SA72HWFNORTHOFYSSURGEDIR, SA72HWFNORTHOFYSWAVENOTES };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增海区72小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改海区72小时海浪预报预报
    /// </summary>
    public int Edit_TBLSEAAREA72HWAVEFORECAST(TBLSEAAREA72HWAVEFORECAST TBLSEAAREA72HWAVEFORECAST)
    {
        string sql = "UPDATE   TBLSEAAREA72HWAVEFORECAST set	SA72HWFMIDDLEOFYSWAVEHEIGHT=@SA72HWFMIDDLEOFYSWAVEHEIGHT,SA72HWFMIDDLEOFYSWAVEDIR=@SA72HWFMIDDLEOFYSWAVEDIR,SA72HWFMIDDLEOFYSSURGEDIR=@SA72HWFMIDDLEOFYSSURGEDIR,SA72HWFMIDDLEOFYSWAVENOTES=@SA72HWFMIDDLEOFYSWAVENOTES,SA72HWFSOUTHOFYSWAVEHEIGHT=@SA72HWFSOUTHOFYSWAVEHEIGHT,SA72HWFSOUTHOFYSWAVEDIR=@SA72HWFSOUTHOFYSWAVEDIR,SA72HWFSOUTHOFYSSURGEDIR=@SA72HWFSOUTHOFYSSURGEDIR,SA72HWFSOUTHOFYSWAVENOTES=@SA72HWFSOUTHOFYSWAVENOTES,SA72HWFBOHAIWAVEHEIGHT=@SA72HWFBOHAIWAVEHEIGHT,SA72HWFBOHAIWAVEDIR=@SA72HWFBOHAIWAVEDIR,SA72HWFBOHAISURGEDIR=@SA72HWFBOHAISURGEDIR,SA72HWFBOHAIWAVENOTES=@SA72HWFBOHAIWAVENOTES,SA72HWFNORTHOFYSWAVEHEIGHT=@SA72HWFNORTHOFYSWAVEHEIGHT,SA72HWFNORTHOFYSWAVEDIR=@SA72HWFNORTHOFYSWAVEDIR,SA72HWFNORTHOFYSSURGEDIR=@SA72HWFNORTHOFYSSURGEDIR,SA72HWFNORTHOFYSWAVENOTES=@SA72HWFNORTHOFYSWAVENOTES where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFMIDDLEOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFSOUTHOFYSWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFBOHAISURGEDIR = DataExe.GetDbParameter();
        var SA72HWFBOHAIWAVENOTES = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVEHEIGHT = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVEDIR = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSSURGEDIR = DataExe.GetDbParameter();
        var SA72HWFNORTHOFYSWAVENOTES = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        SA72HWFMIDDLEOFYSWAVEHEIGHT.ParameterName = "@SA72HWFMIDDLEOFYSWAVEHEIGHT";
        SA72HWFMIDDLEOFYSWAVEDIR.ParameterName = "@SA72HWFMIDDLEOFYSWAVEDIR";
        SA72HWFMIDDLEOFYSSURGEDIR.ParameterName = "@SA72HWFMIDDLEOFYSSURGEDIR";
        SA72HWFMIDDLEOFYSWAVENOTES.ParameterName = "@SA72HWFMIDDLEOFYSWAVENOTES";
        SA72HWFSOUTHOFYSWAVEHEIGHT.ParameterName = "@SA72HWFSOUTHOFYSWAVEHEIGHT";
        SA72HWFSOUTHOFYSWAVEDIR.ParameterName = "@SA72HWFSOUTHOFYSWAVEDIR";
        SA72HWFSOUTHOFYSSURGEDIR.ParameterName = "@SA72HWFSOUTHOFYSSURGEDIR";
        SA72HWFSOUTHOFYSWAVENOTES.ParameterName = "@SA72HWFSOUTHOFYSWAVENOTES";
        SA72HWFBOHAIWAVEHEIGHT.ParameterName = "@SA72HWFBOHAIWAVEHEIGHT";
        SA72HWFBOHAIWAVEDIR.ParameterName = "@SA72HWFBOHAIWAVEDIR";
        SA72HWFBOHAISURGEDIR.ParameterName = "@SA72HWFBOHAISURGEDIR";
        SA72HWFBOHAIWAVENOTES.ParameterName = "@SA72HWFBOHAIWAVENOTES";
        SA72HWFNORTHOFYSWAVEHEIGHT.ParameterName = "@SA72HWFNORTHOFYSWAVEHEIGHT";
        SA72HWFNORTHOFYSWAVEDIR.ParameterName = "@SA72HWFNORTHOFYSWAVEDIR";
        SA72HWFNORTHOFYSSURGEDIR.ParameterName = "@SA72HWFNORTHOFYSSURGEDIR";
        SA72HWFNORTHOFYSWAVENOTES.ParameterName = "@SA72HWFNORTHOFYSWAVENOTES";




        PUBLISHDATE.Value = TBLSEAAREA72HWAVEFORECAST.PUBLISHDATE.ToString();
        SA72HWFMIDDLEOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVEHEIGHT;
        SA72HWFMIDDLEOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVEDIR;
        SA72HWFMIDDLEOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSSURGEDIR;
        SA72HWFMIDDLEOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFMIDDLEOFYSWAVENOTES;
        SA72HWFSOUTHOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVEHEIGHT;
        SA72HWFSOUTHOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVEDIR;
        SA72HWFSOUTHOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSSURGEDIR;
        SA72HWFSOUTHOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFSOUTHOFYSWAVENOTES;
        SA72HWFBOHAIWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVEHEIGHT;
        SA72HWFBOHAIWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVEDIR;
        SA72HWFBOHAISURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAISURGEDIR;
        SA72HWFBOHAIWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFBOHAIWAVENOTES;
        SA72HWFNORTHOFYSWAVEHEIGHT.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVEHEIGHT;
        SA72HWFNORTHOFYSWAVEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVEDIR;
        SA72HWFNORTHOFYSSURGEDIR.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSSURGEDIR;
        SA72HWFNORTHOFYSWAVENOTES.Value = TBLSEAAREA72HWAVEFORECAST.SA72HWFNORTHOFYSWAVENOTES;


        DbParameter[] parameters = { PUBLISHDATE, SA72HWFMIDDLEOFYSWAVEHEIGHT, SA72HWFMIDDLEOFYSWAVEDIR, SA72HWFMIDDLEOFYSSURGEDIR, SA72HWFMIDDLEOFYSWAVENOTES, SA72HWFSOUTHOFYSWAVEHEIGHT, SA72HWFSOUTHOFYSWAVEDIR, SA72HWFSOUTHOFYSSURGEDIR, SA72HWFSOUTHOFYSWAVENOTES, SA72HWFBOHAIWAVEHEIGHT, SA72HWFBOHAIWAVEDIR, SA72HWFBOHAISURGEDIR, SA72HWFBOHAIWAVENOTES, SA72HWFNORTHOFYSWAVEHEIGHT, SA72HWFNORTHOFYSWAVEDIR, SA72HWFNORTHOFYSSURGEDIR, SA72HWFNORTHOFYSWAVENOTES };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改海区72小时海浪预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

