
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 港口潮位
/// </summary>
/// <returns></returns>
public class sql_TBLHARBOURTIDELEVEL
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLHARBOURTIDELEVEL()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有港口潮位预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLHARBOURTIDELEVEL_AllData(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLHARBOURTIDELEVEL where PUBLISHDATE=to_date('" + TBLHARBOURTIDELEVEL.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");
          
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    public object TBLHARBOURTIDELEVELAllData(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {

        try
        {
            string sql = "select * from TBLHARBOURTIDELEVEL "
                    + " where FORECASTDATE > to_date('" + TBLHARBOURTIDELEVEL.FORECASTDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')"
                    + " and FORECASTDATE < to_date('" + TBLHARBOURTIDELEVEL.FORECASTDATE.AddDays(3).ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')"
                    + " and PUBLISHDATE=to_date('" + TBLHARBOURTIDELEVEL.PUBLISHDATE.AddDays(-1).ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')";
            return DataExe.GetTableExeData(sql);

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 新增港口潮位预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLHARBOURTIDELEVEL(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {

        string sql = "INSERT INTO  TBLHARBOURTIDELEVEL (PUBLISHDATE,HTLSECONDTIMELOWTIDE,HTLLOWTIDELEVELFORTHESECONDTIM,HTLHARBOUR,FORECASTDATE,HTLFIRSTWAVEOFTIME,HTLFIRSTWAVETIDELEVEL,HTLFIRSTTIMELOWTIDE,HTLLOWTIDELEVELFORTHEFIRSTTIME,HTLSECONDWAVEOFTIME,HTLSECONDWAVETIDELEVEL) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@HTLSECONDTIMELOWTIDE,@HTLLOWTIDELEVELFORTHESECONDTIM,@HTLHARBOUR,to_date(@FORECASTDATE,'yyyy-mm-dd hh24@mi@ss'),@HTLFIRSTWAVEOFTIME,@HTLFIRSTWAVETIDELEVEL,@HTLFIRSTTIMELOWTIDE,@HTLLOWTIDELEVELFORTHEFIRSTTIME,@HTLSECONDWAVEOFTIME,@HTLSECONDWAVETIDELEVEL)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var HTLSECONDTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHESECONDTIM = DataExe.GetDbParameter();
        var HTLHARBOUR = DataExe.GetDbParameter();
        var FORECASTDATE = DataExe.GetDbParameter();
        var HTLFIRSTWAVEOFTIME = DataExe.GetDbParameter();
        var HTLFIRSTWAVETIDELEVEL = DataExe.GetDbParameter();
        var HTLFIRSTTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHEFIRSTTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVEOFTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVETIDELEVEL = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        HTLSECONDTIMELOWTIDE.ParameterName = "@HTLSECONDTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHESECONDTIM.ParameterName = "@HTLLOWTIDELEVELFORTHESECONDTIM";
        HTLHARBOUR.ParameterName = "@HTLHARBOUR";
        FORECASTDATE.ParameterName = "@FORECASTDATE";
        HTLFIRSTWAVEOFTIME.ParameterName = "@HTLFIRSTWAVEOFTIME";
        HTLFIRSTWAVETIDELEVEL.ParameterName = "@HTLFIRSTWAVETIDELEVEL";
        HTLFIRSTTIMELOWTIDE.ParameterName = "@HTLFIRSTTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHEFIRSTTIME.ParameterName = "@HTLLOWTIDELEVELFORTHEFIRSTTIME";
        HTLSECONDWAVEOFTIME.ParameterName = "@HTLSECONDWAVEOFTIME";
        HTLSECONDWAVETIDELEVEL.ParameterName = "@HTLSECONDWAVETIDELEVEL";




        PUBLISHDATE.Value = TBLHARBOURTIDELEVEL.PUBLISHDATE.ToString();
        HTLSECONDTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLSECONDTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHESECONDTIM.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHESECONDTIM;
        HTLHARBOUR.Value = TBLHARBOURTIDELEVEL.HTLHARBOUR;
        FORECASTDATE.Value = TBLHARBOURTIDELEVEL.FORECASTDATE.ToString();
        HTLFIRSTWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVEOFTIME;
        HTLFIRSTWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVETIDELEVEL;
        HTLFIRSTTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLFIRSTTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHEFIRSTTIME.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHEFIRSTTIME;
        HTLSECONDWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVEOFTIME;
        HTLSECONDWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVETIDELEVEL;


        DbParameter[] parameters = { PUBLISHDATE, HTLSECONDTIMELOWTIDE, HTLLOWTIDELEVELFORTHESECONDTIM, HTLHARBOUR, FORECASTDATE, HTLFIRSTWAVEOFTIME, HTLFIRSTWAVETIDELEVEL, HTLFIRSTTIMELOWTIDE, HTLLOWTIDELEVELFORTHEFIRSTTIME, HTLSECONDWAVEOFTIME, HTLSECONDWAVETIDELEVEL };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改港口潮位预报
    /// </summary>
    public int Edit_TBLHARBOURTIDELEVEL(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {
        string sql = "UPDATE   TBLHARBOURTIDELEVEL set	HTLSECONDTIMELOWTIDE=@HTLSECONDTIMELOWTIDE,HTLLOWTIDELEVELFORTHESECONDTIM=@HTLLOWTIDELEVELFORTHESECONDTIM,HTLFIRSTWAVEOFTIME=@HTLFIRSTWAVEOFTIME,HTLFIRSTWAVETIDELEVEL=@HTLFIRSTWAVETIDELEVEL,HTLFIRSTTIMELOWTIDE=@HTLFIRSTTIMELOWTIDE,HTLLOWTIDELEVELFORTHEFIRSTTIME=@HTLLOWTIDELEVELFORTHEFIRSTTIME,HTLSECONDWAVEOFTIME=@HTLSECONDWAVEOFTIME,HTLSECONDWAVETIDELEVEL=@HTLSECONDWAVETIDELEVEL where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss') and HTLHARBOUR=@HTLHARBOUR and FORECASTDATE=to_date(@FORECASTDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var HTLSECONDTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHESECONDTIM = DataExe.GetDbParameter();
        var HTLHARBOUR = DataExe.GetDbParameter();
        var FORECASTDATE = DataExe.GetDbParameter();
        var HTLFIRSTWAVEOFTIME = DataExe.GetDbParameter();
        var HTLFIRSTWAVETIDELEVEL = DataExe.GetDbParameter();
        var HTLFIRSTTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHEFIRSTTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVEOFTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVETIDELEVEL = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        HTLSECONDTIMELOWTIDE.ParameterName = "@HTLSECONDTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHESECONDTIM.ParameterName = "@HTLLOWTIDELEVELFORTHESECONDTIM";
        HTLHARBOUR.ParameterName = "@HTLHARBOUR";
        FORECASTDATE.ParameterName = "@FORECASTDATE";
        HTLFIRSTWAVEOFTIME.ParameterName = "@HTLFIRSTWAVEOFTIME";
        HTLFIRSTWAVETIDELEVEL.ParameterName = "@HTLFIRSTWAVETIDELEVEL";
        HTLFIRSTTIMELOWTIDE.ParameterName = "@HTLFIRSTTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHEFIRSTTIME.ParameterName = "@HTLLOWTIDELEVELFORTHEFIRSTTIME";
        HTLSECONDWAVEOFTIME.ParameterName = "@HTLSECONDWAVEOFTIME";
        HTLSECONDWAVETIDELEVEL.ParameterName = "@HTLSECONDWAVETIDELEVEL";




        PUBLISHDATE.Value = TBLHARBOURTIDELEVEL.PUBLISHDATE.ToString() ;
        HTLSECONDTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLSECONDTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHESECONDTIM.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHESECONDTIM;
        HTLHARBOUR.Value = TBLHARBOURTIDELEVEL.HTLHARBOUR;
        FORECASTDATE.Value = TBLHARBOURTIDELEVEL.FORECASTDATE.ToString(); 
        HTLFIRSTWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVEOFTIME;
        HTLFIRSTWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVETIDELEVEL;
        HTLFIRSTTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLFIRSTTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHEFIRSTTIME.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHEFIRSTTIME;
        HTLSECONDWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVEOFTIME;
        HTLSECONDWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVETIDELEVEL;


        DbParameter[] parameters = { PUBLISHDATE, HTLSECONDTIMELOWTIDE, HTLLOWTIDELEVELFORTHESECONDTIM, HTLHARBOUR, FORECASTDATE, HTLFIRSTWAVEOFTIME, HTLFIRSTWAVETIDELEVEL, HTLFIRSTTIMELOWTIDE, HTLLOWTIDELEVELFORTHEFIRSTTIME, HTLSECONDWAVEOFTIME, HTLSECONDWAVETIDELEVEL };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }

    /// <summary>
    /// 检索当前预报日期数据
    /// </summary>
    /// <param name="TBLHARBOURTIDELEVEL"></param>
    /// <returns></returns>
    public object GETTBLHARBOURTIDELEVELBYFORECAST(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {

        try
        {
            string sql = "select * from TBLHARBOURTIDELEVEL where "
                + "  FORECASTDATE BETWEEN to_date('" + TBLHARBOURTIDELEVEL.FORECASTDATE.AddDays(1) + "','yyyy-mm-dd hh24@mi@ss') "
                + " and to_date('" + TBLHARBOURTIDELEVEL.FORECASTDATE.AddDays(3) + "','yyyy-mm-dd hh24@mi@ss')";
            return DataExe.GetTableExeData(sql);

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 检索当前预报日期是否存在数据
    /// </summary>
    /// <param name="TBLHARBOURTIDELEVEL"></param>
    /// <returns></returns>
    public object GETTBLHARBOURTIDELEVEL(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {

        try
        {
            string sql = "select * from TBLHARBOURTIDELEVEL where "
                + "  FORECASTDATE=to_date('"+ TBLHARBOURTIDELEVEL.FORECASTDATE + "','yyyy-mm-dd hh24@mi@ss') "
                + " and HTLHARBOUR='"+ TBLHARBOURTIDELEVEL.HTLHARBOUR + "'";
            return DataExe.GetTableExeData(sql);

        }
        catch (Exception ex)
        {
            WriteLog.Write("获取港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 根据预报日期更改数据
    /// </summary>
    /// <param name="TBLHARBOURTIDELEVEL"></param>
    /// <returns></returns>
    public int EDITTBLHARBOURTIDELEVEL(TBLHARBOURTIDELEVEL TBLHARBOURTIDELEVEL)
    {
        string sql = "UPDATE   TBLHARBOURTIDELEVEL set	HTLSECONDTIMELOWTIDE=@HTLSECONDTIMELOWTIDE,HTLLOWTIDELEVELFORTHESECONDTIM=@HTLLOWTIDELEVELFORTHESECONDTIM,HTLFIRSTWAVEOFTIME=@HTLFIRSTWAVEOFTIME,HTLFIRSTWAVETIDELEVEL=@HTLFIRSTWAVETIDELEVEL,HTLFIRSTTIMELOWTIDE=@HTLFIRSTTIMELOWTIDE,HTLLOWTIDELEVELFORTHEFIRSTTIME=@HTLLOWTIDELEVELFORTHEFIRSTTIME,HTLSECONDWAVEOFTIME=@HTLSECONDWAVEOFTIME,HTLSECONDWAVETIDELEVEL=@HTLSECONDWAVETIDELEVEL where "
            + "  HTLHARBOUR=@HTLHARBOUR and FORECASTDATE=to_date(@FORECASTDATE,'yyyy-mm-dd hh24@mi@ss')";

        
        var HTLSECONDTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHESECONDTIM = DataExe.GetDbParameter();
        var HTLHARBOUR = DataExe.GetDbParameter();
        var FORECASTDATE = DataExe.GetDbParameter();
        var HTLFIRSTWAVEOFTIME = DataExe.GetDbParameter();
        var HTLFIRSTWAVETIDELEVEL = DataExe.GetDbParameter();
        var HTLFIRSTTIMELOWTIDE = DataExe.GetDbParameter();
        var HTLLOWTIDELEVELFORTHEFIRSTTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVEOFTIME = DataExe.GetDbParameter();
        var HTLSECONDWAVETIDELEVEL = DataExe.GetDbParameter();


        
        HTLSECONDTIMELOWTIDE.ParameterName = "@HTLSECONDTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHESECONDTIM.ParameterName = "@HTLLOWTIDELEVELFORTHESECONDTIM";
        HTLHARBOUR.ParameterName = "@HTLHARBOUR";
        FORECASTDATE.ParameterName = "@FORECASTDATE";
        HTLFIRSTWAVEOFTIME.ParameterName = "@HTLFIRSTWAVEOFTIME";
        HTLFIRSTWAVETIDELEVEL.ParameterName = "@HTLFIRSTWAVETIDELEVEL";
        HTLFIRSTTIMELOWTIDE.ParameterName = "@HTLFIRSTTIMELOWTIDE";
        HTLLOWTIDELEVELFORTHEFIRSTTIME.ParameterName = "@HTLLOWTIDELEVELFORTHEFIRSTTIME";
        HTLSECONDWAVEOFTIME.ParameterName = "@HTLSECONDWAVEOFTIME";
        HTLSECONDWAVETIDELEVEL.ParameterName = "@HTLSECONDWAVETIDELEVEL";


        
        HTLSECONDTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLSECONDTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHESECONDTIM.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHESECONDTIM;
        HTLHARBOUR.Value = TBLHARBOURTIDELEVEL.HTLHARBOUR;
        FORECASTDATE.Value = TBLHARBOURTIDELEVEL.FORECASTDATE.ToString();
        HTLFIRSTWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVEOFTIME;
        HTLFIRSTWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLFIRSTWAVETIDELEVEL;
        HTLFIRSTTIMELOWTIDE.Value = TBLHARBOURTIDELEVEL.HTLFIRSTTIMELOWTIDE;
        HTLLOWTIDELEVELFORTHEFIRSTTIME.Value = TBLHARBOURTIDELEVEL.HTLLOWTIDELEVELFORTHEFIRSTTIME;
        HTLSECONDWAVEOFTIME.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVEOFTIME;
        HTLSECONDWAVETIDELEVEL.Value = TBLHARBOURTIDELEVEL.HTLSECONDWAVETIDELEVEL;


        DbParameter[] parameters = { HTLSECONDTIMELOWTIDE, HTLLOWTIDELEVELFORTHESECONDTIM, HTLHARBOUR, FORECASTDATE, HTLFIRSTWAVEOFTIME, HTLFIRSTWAVETIDELEVEL, HTLFIRSTTIMELOWTIDE, HTLLOWTIDELEVELFORTHEFIRSTTIME, HTLSECONDWAVEOFTIME, HTLSECONDWAVETIDELEVEL };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改港口潮位出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }
} 




    