
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Web;

/// <summary>
/// 青岛沿岸48小时潮汐预报
/// </summary>
/// <returns></returns>
public class sql_TBLQDCOAST48HTIDALFORECAST
{
    DataExecution DataExe;//声明一个数据执行类
    public sql_TBLQDCOAST48HTIDALFORECAST()
    {
        //
        DataExe = new DataExecution();//使用默认链接字符初始数据库操作类
        //
    }
    /// <summary>
    /// 获取所有青岛沿岸48小时潮汐预报预报
    /// </summary>
    /// <returns></returns>
    public object get_TBLQDCOAST48HTIDALFORECAST_AllData(TBLQDCOAST48HTIDALFORECAST TBLQDCOAST48HTIDALFORECAST)
    {

        try
        {
            return DataExe.GetTableExeData("select * from TBLQDCOAST48HTIDALFORECAST where PUBLISHDATE=to_date('" + TBLQDCOAST48HTIDALFORECAST.PUBLISHDATE.ToString("yyyy-MM-dd") + "', 'yyyy-mm-dd hh24@mi@ss')");
          
        }
        catch (Exception ex)
        {
            WriteLog.Write("获取青岛沿岸48小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }
    /// <summary>
    /// 新增青岛沿岸48小时潮汐预报预报
    /// </summary>
    /// <returns></returns>
    public int Add_TBLQDCOAST48HTIDALFORECAST(TBLQDCOAST48HTIDALFORECAST TBLQDCOAST48HTIDALFORECAST)
    {

        string sql = "INSERT INTO  TBLQDCOAST48HTIDALFORECAST (PUBLISHDATE,QDC48HTFFIRSTLOWWAVEHEIGHT,QDC48HTFSECONDLOWWAVEHOUR,QDC48HTFSECONDLOWWAVEMINUTE,QDC48HTFSECONDLOWWAVEHEIGHT,QDC48HTFFIRSTHIGHWAVEHOUR,QDC48HTFFIRSTHGHWAVEMINUTE,QDC48HTFFIRSTHIGHWAVEHEIGHT,QDC48HTFSECONDHIGHWAVEHOUR,QDC48HTFSECONDHIGHWAVEMINUTE,QDC48HTFSECONDHIGHWAVEHEIGHT,QDC48HTFFIRSTLOWWAVEHOUR,QDC48HTFFIRSTLOWWAVEMINUTE) VALUES (to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss'),@QDC48HTFFIRSTLOWWAVEHEIGHT,@QDC48HTFSECONDLOWWAVEHOUR,@QDC48HTFSECONDLOWWAVEMINUTE,@QDC48HTFSECONDLOWWAVEHEIGHT,@QDC48HTFFIRSTHIGHWAVEHOUR,@QDC48HTFFIRSTHGHWAVEMINUTE,@QDC48HTFFIRSTHIGHWAVEHEIGHT,@QDC48HTFSECONDHIGHWAVEHOUR,@QDC48HTFSECONDHIGHWAVEMINUTE,@QDC48HTFSECONDHIGHWAVEHEIGHT,@QDC48HTFFIRSTLOWWAVEHOUR,@QDC48HTFFIRSTLOWWAVEMINUTE)";



        var PUBLISHDATE = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHIGHWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHGHWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEMINUTE = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        QDC48HTFFIRSTLOWWAVEHEIGHT.ParameterName = "@QDC48HTFFIRSTLOWWAVEHEIGHT";
        QDC48HTFSECONDLOWWAVEHOUR.ParameterName = "@QDC48HTFSECONDLOWWAVEHOUR";
        QDC48HTFSECONDLOWWAVEMINUTE.ParameterName = "@QDC48HTFSECONDLOWWAVEMINUTE";
        QDC48HTFSECONDLOWWAVEHEIGHT.ParameterName = "@QDC48HTFSECONDLOWWAVEHEIGHT";
        QDC48HTFFIRSTHIGHWAVEHOUR.ParameterName = "@QDC48HTFFIRSTHIGHWAVEHOUR";
        QDC48HTFFIRSTHGHWAVEMINUTE.ParameterName = "@QDC48HTFFIRSTHGHWAVEMINUTE";
        QDC48HTFFIRSTHIGHWAVEHEIGHT.ParameterName = "@QDC48HTFFIRSTHIGHWAVEHEIGHT";
        QDC48HTFSECONDHIGHWAVEHOUR.ParameterName = "@QDC48HTFSECONDHIGHWAVEHOUR";
        QDC48HTFSECONDHIGHWAVEMINUTE.ParameterName = "@QDC48HTFSECONDHIGHWAVEMINUTE";
        QDC48HTFSECONDHIGHWAVEHEIGHT.ParameterName = "@QDC48HTFSECONDHIGHWAVEHEIGHT";
        QDC48HTFFIRSTLOWWAVEHOUR.ParameterName = "@QDC48HTFFIRSTLOWWAVEHOUR";
        QDC48HTFFIRSTLOWWAVEMINUTE.ParameterName = "@QDC48HTFFIRSTLOWWAVEMINUTE";




        PUBLISHDATE.Value = TBLQDCOAST48HTIDALFORECAST.PUBLISHDATE.ToString();
        QDC48HTFFIRSTLOWWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEHEIGHT;
        QDC48HTFSECONDLOWWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEHOUR;
        QDC48HTFSECONDLOWWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEMINUTE;
        QDC48HTFSECONDLOWWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEHEIGHT;
        QDC48HTFFIRSTHIGHWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHIGHWAVEHOUR;
        QDC48HTFFIRSTHGHWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHGHWAVEMINUTE;
        QDC48HTFFIRSTHIGHWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHIGHWAVEHEIGHT;
        QDC48HTFSECONDHIGHWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEHOUR;
        QDC48HTFSECONDHIGHWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEMINUTE;
        QDC48HTFSECONDHIGHWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEHEIGHT;
        QDC48HTFFIRSTLOWWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEHOUR;
        QDC48HTFFIRSTLOWWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEMINUTE;


        DbParameter[] parameters = { PUBLISHDATE, QDC48HTFFIRSTLOWWAVEHEIGHT, QDC48HTFSECONDLOWWAVEHOUR, QDC48HTFSECONDLOWWAVEMINUTE, QDC48HTFSECONDLOWWAVEHEIGHT, QDC48HTFFIRSTHIGHWAVEHOUR, QDC48HTFFIRSTHGHWAVEMINUTE, QDC48HTFFIRSTHIGHWAVEHEIGHT, QDC48HTFSECONDHIGHWAVEHOUR, QDC48HTFSECONDHIGHWAVEMINUTE, QDC48HTFSECONDHIGHWAVEHEIGHT, QDC48HTFFIRSTLOWWAVEHOUR, QDC48HTFFIRSTLOWWAVEMINUTE };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("新增青岛沿岸48小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }
    }

    /// <summary>
    /// 修改青岛沿岸48小时潮汐预报预报
    /// </summary>
    public int Edit_TBLQDCOAST48HTIDALFORECAST(TBLQDCOAST48HTIDALFORECAST TBLQDCOAST48HTIDALFORECAST)
    {
        string sql = "UPDATE   TBLQDCOAST48HTIDALFORECAST set	QDC48HTFFIRSTLOWWAVEHEIGHT=@QDC48HTFFIRSTLOWWAVEHEIGHT,QDC48HTFSECONDLOWWAVEHOUR=@QDC48HTFSECONDLOWWAVEHOUR,QDC48HTFSECONDLOWWAVEMINUTE=@QDC48HTFSECONDLOWWAVEMINUTE,QDC48HTFSECONDLOWWAVEHEIGHT=@QDC48HTFSECONDLOWWAVEHEIGHT,QDC48HTFFIRSTHIGHWAVEHOUR=@QDC48HTFFIRSTHIGHWAVEHOUR,QDC48HTFFIRSTHGHWAVEMINUTE=@QDC48HTFFIRSTHGHWAVEMINUTE,QDC48HTFFIRSTHIGHWAVEHEIGHT=@QDC48HTFFIRSTHIGHWAVEHEIGHT,QDC48HTFSECONDHIGHWAVEHOUR=@QDC48HTFSECONDHIGHWAVEHOUR,QDC48HTFSECONDHIGHWAVEMINUTE=@QDC48HTFSECONDHIGHWAVEMINUTE,QDC48HTFSECONDHIGHWAVEHEIGHT=@QDC48HTFSECONDHIGHWAVEHEIGHT,QDC48HTFFIRSTLOWWAVEHOUR=@QDC48HTFFIRSTLOWWAVEHOUR,QDC48HTFFIRSTLOWWAVEMINUTE=@QDC48HTFFIRSTLOWWAVEMINUTE where PUBLISHDATE=to_date(@PUBLISHDATE,'yyyy-mm-dd hh24@mi@ss')";


        var PUBLISHDATE = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFSECONDLOWWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHIGHWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHGHWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFFIRSTHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEMINUTE = DataExe.GetDbParameter();
        var QDC48HTFSECONDHIGHWAVEHEIGHT = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEHOUR = DataExe.GetDbParameter();
        var QDC48HTFFIRSTLOWWAVEMINUTE = DataExe.GetDbParameter();




        PUBLISHDATE.ParameterName = "@PUBLISHDATE";
        QDC48HTFFIRSTLOWWAVEHEIGHT.ParameterName = "@QDC48HTFFIRSTLOWWAVEHEIGHT";
        QDC48HTFSECONDLOWWAVEHOUR.ParameterName = "@QDC48HTFSECONDLOWWAVEHOUR";
        QDC48HTFSECONDLOWWAVEMINUTE.ParameterName = "@QDC48HTFSECONDLOWWAVEMINUTE";
        QDC48HTFSECONDLOWWAVEHEIGHT.ParameterName = "@QDC48HTFSECONDLOWWAVEHEIGHT";
        QDC48HTFFIRSTHIGHWAVEHOUR.ParameterName = "@QDC48HTFFIRSTHIGHWAVEHOUR";
        QDC48HTFFIRSTHGHWAVEMINUTE.ParameterName = "@QDC48HTFFIRSTHGHWAVEMINUTE";
        QDC48HTFFIRSTHIGHWAVEHEIGHT.ParameterName = "@QDC48HTFFIRSTHIGHWAVEHEIGHT";
        QDC48HTFSECONDHIGHWAVEHOUR.ParameterName = "@QDC48HTFSECONDHIGHWAVEHOUR";
        QDC48HTFSECONDHIGHWAVEMINUTE.ParameterName = "@QDC48HTFSECONDHIGHWAVEMINUTE";
        QDC48HTFSECONDHIGHWAVEHEIGHT.ParameterName = "@QDC48HTFSECONDHIGHWAVEHEIGHT";
        QDC48HTFFIRSTLOWWAVEHOUR.ParameterName = "@QDC48HTFFIRSTLOWWAVEHOUR";
        QDC48HTFFIRSTLOWWAVEMINUTE.ParameterName = "@QDC48HTFFIRSTLOWWAVEMINUTE";




        PUBLISHDATE.Value = TBLQDCOAST48HTIDALFORECAST.PUBLISHDATE.ToString();
        QDC48HTFFIRSTLOWWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEHEIGHT;
        QDC48HTFSECONDLOWWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEHOUR;
        QDC48HTFSECONDLOWWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEMINUTE;
        QDC48HTFSECONDLOWWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDLOWWAVEHEIGHT;
        QDC48HTFFIRSTHIGHWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHIGHWAVEHOUR;
        QDC48HTFFIRSTHGHWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHGHWAVEMINUTE;
        QDC48HTFFIRSTHIGHWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTHIGHWAVEHEIGHT;
        QDC48HTFSECONDHIGHWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEHOUR;
        QDC48HTFSECONDHIGHWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEMINUTE;
        QDC48HTFSECONDHIGHWAVEHEIGHT.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFSECONDHIGHWAVEHEIGHT;
        QDC48HTFFIRSTLOWWAVEHOUR.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEHOUR;
        QDC48HTFFIRSTLOWWAVEMINUTE.Value = TBLQDCOAST48HTIDALFORECAST.QDC48HTFFIRSTLOWWAVEMINUTE;


        DbParameter[] parameters = { PUBLISHDATE, QDC48HTFFIRSTLOWWAVEHEIGHT, QDC48HTFSECONDLOWWAVEHOUR, QDC48HTFSECONDLOWWAVEMINUTE, QDC48HTFSECONDLOWWAVEHEIGHT, QDC48HTFFIRSTHIGHWAVEHOUR, QDC48HTFFIRSTHGHWAVEMINUTE, QDC48HTFFIRSTHIGHWAVEHEIGHT, QDC48HTFSECONDHIGHWAVEHOUR, QDC48HTFSECONDHIGHWAVEMINUTE, QDC48HTFSECONDHIGHWAVEHEIGHT, QDC48HTFFIRSTLOWWAVEHOUR, QDC48HTFFIRSTLOWWAVEMINUTE };
        try
        {
            return DataExe.GetIntExeData(sql, parameters);
        }
        catch (Exception ex)
        {
            WriteLog.Write("修改青岛沿岸48小时潮汐预报出现异常！" + ex.Message + "\r\n" + ex.StackTrace);
            return 0;
        }


    }


}

